import React from 'react';
import { render, screen, fireEvent, waitFor } from '@testing-library/react';

// Mock dependent hooks before importing the hook under test
const openAddModalMock = jest.fn();
const openTranscriptViewerMock = jest.fn();

const mockAnalyzeQuote = jest.fn().mockResolvedValue({ data: { score: 85 } });
const mockUpdateQuote = jest.fn().mockResolvedValue({ data: {} });
const mockHandleExtractQuotes = jest.fn();

jest.mock('../useAuth', () => ({
  useAuth: () => ({
    user: { _id: 'u1', email: 'dev@example.com', name: 'Dev', alias: 'dev', role: 'admin' },
    loginError: null,
    googleButtonRef: { current: null },
    handleLogout: jest.fn(),
    loginWithPassword: jest.fn(),
    updateUser: jest.fn(),
  })
}));

jest.mock('../useSearchParams', () => ({
  useSearchParams: () => ({
    isExtracting: false,
    setIsExtracting: jest.fn(),
    personName: '',
    selectedAI: '',
    selectedLanguages: [],
    resultCount: 5,
    temperature: 0.2,
    maxQuoteLength: 300,
    textToExtract: '',
    setTextToExtract: jest.fn(),
    clearTextToExtract: jest.fn(),
    isAgentic: false,
    agenticMode: 'quotes',
  })
}));

jest.mock('../useTimePeriod', () => ({
  useTimePeriod: () => ({ getTimePeriod: () => ({ startDate: '2025-01-01', endDate: '2025-12-31' }) })
}));

jest.mock('../useQuotes', () => ({
  useQuotes: () => ({
    quotes: [],
    articles: [],
    isLoading: false,
    error: null,
    rawApiResponseError: null,
    handleLoadQuotes: jest.fn(),
    handleSearch: jest.fn(),
    handleAnalyzeQuote: jest.fn(),
    handleImproveQuote: jest.fn(),
    handleExtractQuotes: mockHandleExtractQuotes,
    handleExtractFromUrl: jest.fn().mockResolvedValue([]),
    handleAddQuoteManually: jest.fn((p, t, d, cb) => cb && cb({ id: 'q1' })),
    handleCancelSearch: jest.fn(),
    handleUpdateQuoteLanguage: jest.fn(),
    handleAcceptQuote: jest.fn(),
    handleDiscardQuote: jest.fn(),
    handleRemoveQuote: jest.fn(),
    clearError: jest.fn(),
  })
}));

jest.mock('../useQuoteFilters', () => ({
  useQuoteFilters: () => ({
    sortOrder: 'newest',
    setSortOrder: jest.fn(),
    filterCategory: 'all',
    filterRating: 'all',
    filteredAndSortedQuotes: [],
  })
}));

jest.mock('../useUIState', () => ({
  useUIState: () => ({
    isFormCollapsed: false,
    toggleFormCollapsed: jest.fn(),
    isAddModalOpen: false,
    openAddModal: openAddModalMock,
    closeAddModal: jest.fn(),
    openTranscriptViewer: openTranscriptViewerMock,
    closeTranscriptViewer: jest.fn(),
    transcriptData: null,
    updateTranscriptSessionId: jest.fn(),
  })
}));

// Mock API utilities to avoid import.meta usage and network calls
jest.mock('../../utils/api', () => ({
  fetchArticle: jest.fn().mockResolvedValue({ data: { textContent: '', metadata: { url: '' }, transcript: null } }),
  getSession: jest.fn().mockResolvedValue({ data: {} }),
  getContentAnalysis: jest.fn().mockResolvedValue({ data: {} }),
  saveQuote: jest.fn().mockResolvedValue({ data: {} }),
  fetchSystemSettings: jest.fn().mockResolvedValue({ search: true, text_extract: true }),
  updateSystemSettings: jest.fn().mockResolvedValue({ search: true, text_extract: true }),
  analyzeQuote: mockAnalyzeQuote,
  updateQuote: mockUpdateQuote,
}));

// Import the hook under test after mocking
import { useAppController } from '../useAppController';
import { I18nProvider } from '../../i18n';

const TestComponent: React.FC = () => {
  const ctrl = useAppController();

  return (
    <div>
      <button onClick={() => ctrl.openAddQuoteModal()}>open-add</button>
      <button onClick={() => ctrl.openExtractModal()}>open-extract</button>
      <button onClick={() => (ctrl as any).handleImportTranscript({ videoId: 'vid', languageCode: 'en', isAutoGenerated: false, segments: [] })}>import-transcript</button>
      <button onClick={() => ctrl.performExtraction({}, 'gpt-4', 'audit', true)}>perform-extraction</button>
      <span data-testid="modalMode">{ctrl.modalMode}</span>
      <span data-testid="isAddOpen">{String(ctrl.isAddModalOpen)}</span>
      <span data-testid="shouldAnalyze">{String(ctrl.shouldAnalyzeImmediately)}</span>
      <span data-testid="refreshTrigger">{ctrl.storedQuotesRefreshTrigger}</span>
    </div>
  );
};

describe('useAppController', () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  it('openAddQuoteModal sets modalMode and triggers UI open', async () => {
    render(<I18nProvider><TestComponent /></I18nProvider>);

    fireEvent.click(screen.getByText('open-add'));

    await waitFor(() => {
      expect(openAddModalMock).toHaveBeenCalled();
      expect(screen.getByTestId('modalMode').textContent).toBe('add');
      expect(screen.getByTestId('shouldAnalyze').textContent).toBe('true');
    });
  });

  it('openExtractModal sets modalMode to extract and opens modal', async () => {
    render(<I18nProvider><TestComponent /></I18nProvider>);

    fireEvent.click(screen.getByText('open-extract'));

    await waitFor(() => {
      expect(openAddModalMock).toHaveBeenCalled();
      expect(screen.getByTestId('modalMode').textContent).toBe('extract');
    });
  });

  it('handleImportTranscript calls uiState.openTranscriptViewer with provided data', async () => {
    render(<I18nProvider><TestComponent /></I18nProvider>);

    fireEvent.click(screen.getByText('import-transcript'));

    await waitFor(() => {
      expect(openTranscriptViewerMock).toHaveBeenCalledWith({
        videoId: 'vid',
        languageCode: 'en',
        isAutoGenerated: false,
        segments: [],
      });
    });
  });

  it('performExtraction analyzes retrieved quotes immediately and updates refresh trigger', async () => {
    // Setup mock implementation to call the callback immediately with new quotes
    mockHandleExtractQuotes.mockImplementation((model, person, text, details, callback) => {
      // Simulate extraction returning one new quote
      const newQuotes = [{
        id: 'new1',
        text: 'New quote text',
        languageCode: 'en',
        languageName: 'English',
        analysisContext: 'Context',
        links: [],
        person: { _id: 'p1' },
        personName: 'Person',
        metadata: { originalMetadata: true }
      }];
      // Call the callback provided by useAppController
      return callback(newQuotes);
    });

    render(<I18nProvider><TestComponent /></I18nProvider>);

    // Initial value check
    expect(screen.getByTestId('refreshTrigger').textContent).toBe('0');

    // Trigger extraction
    fireEvent.click(screen.getByText('perform-extraction'));

    await waitFor(() => {
      // Verify extraction called
      expect(mockHandleExtractQuotes).toHaveBeenCalled();

      // Verify analysis was called for the new quote
      expect(mockAnalyzeQuote).toHaveBeenCalledWith(
        'gpt-4',
        'New quote text',
        'en',
        'English',
        'Context',
        [],
        'p1',
        'Person',
        'audit'
      );

      // Verify update was called with result
      expect(mockUpdateQuote).toHaveBeenCalledWith('new1', expect.objectContaining({
        metadata: expect.objectContaining({
          audit: { score: 85 },
          analyzedByProvider: 'gpt-4'
        })
      }));

      // Verify refresh trigger updated (0 -> 1)
      expect(screen.getByTestId('refreshTrigger').textContent).toBe('1');
    });
  });
});