import React from 'react';
import { render, screen, fireEvent, waitFor } from '@testing-library/react';

// Mock dependent hooks before importing the hook under test
const openAddModalMock = jest.fn();
const openTranscriptViewerMock = jest.fn();

jest.mock('../useAuth', () => ({
  useAuth: () => ({
    user: { _id: 'u1', email: 'dev@example.com', name: 'Dev', alias: 'dev', role: 'admin' },
    loginError: null,
    googleButtonRef: { current: null },
    handleLogout: jest.fn(),
    loginWithPassword: jest.fn(),
    updateUser: jest.fn(),
  })
}));

jest.mock('../useSearchParams', () => ({
  useSearchParams: () => ({
    isExtracting: false,
    setIsExtracting: jest.fn(),
    personName: '',
    selectedAI: '',
    selectedLanguages: [],
    resultCount: 5,
    temperature: 0.2,
    maxQuoteLength: 300,
    textToExtract: '',
    setTextToExtract: jest.fn(),
    clearTextToExtract: jest.fn(),
    isAgentic: false,
    agenticMode: 'quotes',
  })
}));

jest.mock('../useTimePeriod', () => ({
  useTimePeriod: () => ({ getTimePeriod: () => ({ startDate: '2025-01-01', endDate: '2025-12-31' }) })
}));

jest.mock('../useQuotes', () => ({
  useQuotes: () => ({
    quotes: [],
    articles: [],
    isLoading: false,
    error: null,
    rawApiResponseError: null,
    handleLoadQuotes: jest.fn(),
    handleSearch: jest.fn(),
    handleAnalyzeQuote: jest.fn(),
    handleImproveQuote: jest.fn(),
    handleExtractQuotes: jest.fn().mockResolvedValue([]),
    handleExtractFromUrl: jest.fn().mockResolvedValue([]),
    handleAddQuoteManually: jest.fn((p, t, d, cb) => cb && cb({ id: 'q1' })),
    handleCancelSearch: jest.fn(),
    handleUpdateQuoteLanguage: jest.fn(),
    handleAcceptQuote: jest.fn(),
    handleDiscardQuote: jest.fn(),
    handleRemoveQuote: jest.fn(),
    clearError: jest.fn(),
  })
}));

jest.mock('../useQuoteFilters', () => ({
  useQuoteFilters: () => ({
    sortOrder: 'newest',
    setSortOrder: jest.fn(),
    filterCategory: 'all',
    filterRating: 'all',
    filteredAndSortedQuotes: [],
  })
}));

jest.mock('../useUIState', () => ({
  useUIState: () => ({
    isFormCollapsed: false,
    toggleFormCollapsed: jest.fn(),
    isAddModalOpen: false,
    openAddModal: openAddModalMock,
    closeAddModal: jest.fn(),
    openTranscriptViewer: openTranscriptViewerMock,
    closeTranscriptViewer: jest.fn(),
    transcriptData: null,
    updateTranscriptSessionId: jest.fn(),
  })
}));

// Mock API utilities to avoid import.meta usage and network calls
jest.mock('../../utils/api', () => ({
  fetchArticle: jest.fn().mockResolvedValue({ data: { textContent: '', metadata: { url: '' }, transcript: null } }),
  getSession: jest.fn().mockResolvedValue({ data: {} }),
  getContentAnalysis: jest.fn().mockResolvedValue({ data: {} }),
  saveQuote: jest.fn().mockResolvedValue({ data: {} }),
  fetchSystemSettings: jest.fn().mockResolvedValue({ search: true, text_extract: true }),
  updateSystemSettings: jest.fn().mockResolvedValue({ search: true, text_extract: true }),
}));

// Import the hook under test after mocking
import { useAppController } from '../useAppController';
import { I18nProvider } from '../../i18n';

const TestComponent: React.FC = () => {
  const ctrl = useAppController();

  return (
    <div>
      <button onClick={() => ctrl.openAddQuoteModal(true)}>open-add</button>
      <button onClick={() => ctrl.openExtractModal()}>open-extract</button>
      <button onClick={() => (ctrl as any).handleImportTranscript({ videoId: 'vid', languageCode: 'en', isAutoGenerated: false, segments: [] })}>import-transcript</button>
      <span data-testid="modalMode">{ctrl.modalMode}</span>
      <span data-testid="isAddOpen">{String(ctrl.isAddModalOpen)}</span>
      <span data-testid="shouldAnalyze">{String(ctrl.shouldAnalyzeImmediately)}</span>
    </div>
  );
};

describe('useAppController', () => {
  it('openAddQuoteModal sets modalMode and triggers UI open', async () => {
    render(<I18nProvider><TestComponent /></I18nProvider>);

    fireEvent.click(screen.getByText('open-add'));

    await waitFor(() => {
      expect(openAddModalMock).toHaveBeenCalled();
      expect(screen.getByTestId('modalMode').textContent).toBe('add');
      expect(screen.getByTestId('shouldAnalyze').textContent).toBe('true');
    });
  });

  it('openExtractModal sets modalMode to extract and opens modal', async () => {
    render(<I18nProvider><TestComponent /></I18nProvider>);

    fireEvent.click(screen.getByText('open-extract'));

    await waitFor(() => {
      expect(openAddModalMock).toHaveBeenCalled();
      expect(screen.getByTestId('modalMode').textContent).toBe('extract');
    });
  });

  it('handleImportTranscript calls uiState.openTranscriptViewer with provided data', async () => {
    render(<I18nProvider><TestComponent /></I18nProvider>);

    fireEvent.click(screen.getByText('import-transcript'));

    await waitFor(() => {
      expect(openTranscriptViewerMock).toHaveBeenCalledWith({
        videoId: 'vid',
        languageCode: 'en',
        isAutoGenerated: false,
        segments: [],
      });
    });
  });
});