import React from 'react';
import { render, screen, fireEvent } from '@testing-library/react';

// Mock child modal components
jest.mock('../AddQuoteModal', () => ({
  __esModule: true,
  default: ({ isOpen, onClose, onSave, mode, initialSource }: any) =>
    isOpen ? (
      <div data-testid="add-modal" data-mode={mode} data-source={initialSource}>
        <button data-testid="save" onClick={() => onSave({ saved: true })}>save</button>
        <button data-testid="close" onClick={onClose}>close</button>
      </div>
    ) : null,
}));

jest.mock('../ApiKeySettingsModal', () => ({
  __esModule: true,
  default: ({ isOpen, onClose }: any) => isOpen ? <div data-testid="api-key-modal"><button data-testid="api-close" onClick={onClose}>close</button></div> : null,
}));

jest.mock('../TranscriptMethodSelector', () => ({
  __esModule: true,
  TranscriptMethodSelector: ({ isOpen, onClose, onImport, onAutoFetch, isLoading, autoFetchError }: any) =>
    isOpen ? (
      <div data-testid="transcript-selector">
        <button data-testid="import" onClick={() => onImport({ videoId: 'vid', languageCode: 'en', isAutoGenerated: false, segments: [] })}>import</button>
        <button data-testid="autofetch" onClick={() => onAutoFetch('https://youtube.com/watch?v=abc')}>autofetch</button>
        <button data-testid="close-ts" onClick={onClose}>close</button>
        <div data-testid="auto-error">{autoFetchError || ''}</div>
        <div data-testid="is-loading">{String(isLoading)}</div>
      </div>
    ) : null,
}));

jest.mock('../users/PasswordModal', () => ({
  __esModule: true,
  PasswordModal: ({ user, onClose, onSubmit }: any) => (
    <div data-testid="password-modal">
      <div>{user?.name}</div>
      <button data-testid="pw-submit" onClick={() => onSubmit()}>submit</button>
      <button data-testid="pw-close" onClick={onClose}>close</button>
    </div>
  ),
}));

jest.mock('../users/UserChangePasswordModal', () => ({
  __esModule: true,
  UserChangePasswordModal: ({ onClose, onSubmit }: any) => (
    <div data-testid="password-modal">
      <button data-testid="pw-submit" onClick={() => onSubmit()}>submit</button>
      <button data-testid="pw-close" onClick={onClose}>close</button>
    </div>
  ),
}));

jest.mock('../users/EditProfileModal', () => ({
  __esModule: true,
  EditProfileModal: ({ user, onClose, onSubmit }: any) => (
    <div data-testid="edit-profile-modal">
      <div>{user?.name}</div>
      <button data-testid="profile-submit" onClick={() => onSubmit('New Name')}>submit</button>
      <button data-testid="profile-close" onClick={onClose}>close</button>
    </div>
  ),
}));

jest.mock('../admin/UsageStatsDashboard', () => ({
  __esModule: true,
  UsageStatsDashboard: ({ onClose }: any) => (
    <div data-testid="usage-dashboard">
      <button data-testid="dashboard-close" onClick={onClose}>close</button>
    </div>
  ),
}));

import ModalsContainer from '../modals/ModalsContainer';

describe('ModalsContainer', () => {
  it('renders AddQuoteModal and calls onSave/onClose', () => {
    const onSave = jest.fn();
    const closeAddModal = jest.fn();

    render(
      <ModalsContainer
        isAddModalOpen={true}
        closeAddModal={closeAddModal}
        onSave={onSave}
        mode={'add'}
        initialSource={'http://example.com'}

        isApiKeyModalOpen={false}
        onCloseApiKeyModal={() => { }}

        isTranscriptMethodSelectorOpen={false}
        onCloseTranscriptMethodSelector={() => { }}
        onImportTranscript={() => { }}
        onAutoFetchTranscript={async () => { }}
        autoFetchError={null}
        isExtracting={false}

        isChangePasswordModalOpen={false}
        isEditProfileModalOpen={false}
        user={null}
        onPasswordUpdated={() => { }}
        closeChangePasswordModal={() => { }}
        onProfileUpdated={() => { }}

        isUsageStatsDashboardOpen={false}
        onCloseUsageStats={() => { }}
      />
    );

    expect(screen.getByTestId('add-modal')).toBeInTheDocument();
    expect(screen.getByTestId('add-modal')).toHaveAttribute('data-mode', 'add');
    expect(screen.getByTestId('add-modal')).toHaveAttribute('data-source', 'http://example.com');

    fireEvent.click(screen.getByTestId('save'));
    expect(onSave).toHaveBeenCalledWith({ saved: true });

    fireEvent.click(screen.getByTestId('close'));
    expect(closeAddModal).toHaveBeenCalled();
  });

  it('transcript selector triggers import and autofetch and closes on import', async () => {
    const onImport = jest.fn();
    const onCloseTS = jest.fn();
    const onAutoFetch = jest.fn().mockResolvedValue(undefined);

    render(
      <ModalsContainer
        isAddModalOpen={false}
        closeAddModal={() => { }}
        onSave={() => { }}
        mode={'extract'}
        initialSource={''}

        isApiKeyModalOpen={false}
        onCloseApiKeyModal={() => { }}

        isTranscriptMethodSelectorOpen={true}
        onCloseTranscriptMethodSelector={onCloseTS}
        onImportTranscript={onImport}
        onAutoFetchTranscript={onAutoFetch}
        autoFetchError={'err-msg'}
        isExtracting={true}

        isChangePasswordModalOpen={false}
        isEditProfileModalOpen={false}
        user={null}
        onPasswordUpdated={() => { }}
        closeChangePasswordModal={() => { }}
        onProfileUpdated={() => { }}

        isUsageStatsDashboardOpen={false}
        onCloseUsageStats={() => { }}
      />
    );

    expect(screen.getByTestId('transcript-selector')).toBeInTheDocument();
    expect(screen.getByTestId('auto-error').textContent).toBe('err-msg');
    expect(screen.getByTestId('is-loading').textContent).toBe('true');

    fireEvent.click(screen.getByTestId('autofetch'));
    expect(onAutoFetch).toHaveBeenCalledWith('https://youtube.com/watch?v=abc');

    fireEvent.click(screen.getByTestId('import'));
    expect(onImport).toHaveBeenCalledWith({ videoId: 'vid', languageCode: 'en', isAutoGenerated: false, segments: [] });
    // ModalsContainer wraps onImport to call onClose as well
    expect(onCloseTS).toHaveBeenCalled();
  });

  it('renders password and profile modals and calls callbacks', () => {
    const onPwUpdated = jest.fn();
    const onProfileUpdated = jest.fn();

    render(
      <ModalsContainer
        isAddModalOpen={false}
        closeAddModal={() => { }}
        onSave={() => { }}
        mode={'add'}
        initialSource={''}

        isApiKeyModalOpen={false}
        onCloseApiKeyModal={() => { }}

        isTranscriptMethodSelectorOpen={false}
        onCloseTranscriptMethodSelector={() => { }}
        onImportTranscript={() => { }}
        onAutoFetchTranscript={async () => { }}
        autoFetchError={null}
        isExtracting={false}

        isChangePasswordModalOpen={true}
        isEditProfileModalOpen={true}
        user={{ _id: 'u1', name: 'User' }}
        onPasswordUpdated={onPwUpdated}
        closeChangePasswordModal={() => { }}
        onProfileUpdated={onProfileUpdated}

        isUsageStatsDashboardOpen={false}
        onCloseUsageStats={() => { }}
      />
    );

    expect(screen.getByTestId('password-modal')).toBeInTheDocument();
    fireEvent.click(screen.getByTestId('pw-submit'));
    expect(onPwUpdated).toHaveBeenCalled();

    expect(screen.getByTestId('edit-profile-modal')).toBeInTheDocument();
    fireEvent.click(screen.getByTestId('profile-submit'));
    expect(onProfileUpdated).toHaveBeenCalledWith('New Name');
  });

  it('renders usage dashboard and calls onClose', () => {
    const onClose = jest.fn();

    render(
      <ModalsContainer
        isAddModalOpen={false}
        closeAddModal={() => { }}
        onSave={() => { }}
        mode={'add'}
        initialSource={''}

        isApiKeyModalOpen={false}
        onCloseApiKeyModal={() => { }}

        isTranscriptMethodSelectorOpen={false}
        onCloseTranscriptMethodSelector={() => { }}
        onImportTranscript={() => { }}
        onAutoFetchTranscript={async () => { }}
        autoFetchError={null}
        isExtracting={false}

        isChangePasswordModalOpen={false}
        isEditProfileModalOpen={false}
        user={null}
        onPasswordUpdated={() => { }}
        closeChangePasswordModal={() => { }}
        onProfileUpdated={() => { }}

        isUsageStatsDashboardOpen={true}
        onCloseUsageStats={onClose}
      />
    );

    expect(screen.getByTestId('usage-dashboard')).toBeInTheDocument();
    fireEvent.click(screen.getByTestId('dashboard-close'));
    expect(onClose).toHaveBeenCalled();
  });
});