import React from 'react';
import { useAuth } from './useAuth';
import { useSearchParams } from './useSearchParams';
import { useTimePeriod } from './useTimePeriod';
import { useQuotes } from './useQuotes';
import { useQuoteFilters } from './useQuoteFilters';
import { useUIState } from './useUIState';
import { fetchArticle, getSession, getContentAnalysis } from '../utils/api';
import { exportQuotesToFile, importQuotesFromFile } from '../utils/file';
import { saveQuote } from '../utils/api';
import { TranscriptData } from '../utils/transcriptStorage';
import { FullAnalysisData } from '../utils/analysisStorage';
import type { Quote, Person, AnalysisSession, ExportData } from '../types';

export type UseAppController = ReturnType<typeof useAppController>;

export function useAppController() {
  const { user, loginError, googleButtonRef, handleLogout, loginWithPassword, updateUser } = useAuth();

  const searchParams = useSearchParams();
  const timePeriod = useTimePeriod();
  const quotesState = useQuotes(handleLogout);
  const quoteFilters = useQuoteFilters(quotesState.quotes);
  const uiState = useUIState();

  // Local UI flags
  const [logsVisible, setLogsVisible] = React.useState(false);
  const [isApiKeyModalOpen, setIsApiKeyModalOpen] = React.useState(false);
  const [isChangePasswordModalOpen, setIsChangePasswordModalOpen] = React.useState(false);
  const [isEditProfileModalOpen, setIsEditProfileModalOpen] = React.useState(false);
  const [modalMode, setModalMode] = React.useState<'add' | 'extract'>('add');
  const [activeTab, setActiveTab] = React.useState<'search' | 'people' | 'users' | 'sessions'>('search');
  const [resultsTab, setResultsTab] = React.useState<'new' | 'stored' | 'transcript'>('new');
  const [selectedPerson, setSelectedPerson] = React.useState<Person | null>(null);
  const [sessionsRefreshTrigger, setSessionsRefreshTrigger] = React.useState(0);
  const [extractionStatus, setExtractionStatus] = React.useState<string>('');
  const [extractionLanguage, setExtractionLanguage] = React.useState<string>('lt');
  const [extractionError, setExtractionError] = React.useState<string | null>(null);
  const [extractedSourceUrl, setExtractedSourceUrl] = React.useState<string>('');
  const [shouldAnalyzeImmediately, setShouldAnalyzeImmediately] = React.useState<boolean>(true);
  const [isUsageStatsDashboardOpen, setIsUsageStatsDashboardOpen] = React.useState<boolean>(false);
  const [isAdminBannerCollapsed, setIsAdminBannerCollapsed] = React.useState<boolean>(true);
  const [isTranscriptMethodSelectorOpen, setIsTranscriptMethodSelectorOpen] = React.useState<boolean>(false);
  const [autoFetchError, setAutoFetchError] = React.useState<string | null>(null);

  React.useEffect(() => {
    if (logsVisible) {
      uiState.setIsFormCollapsed(true);
    }
  }, [logsVisible, uiState.setIsFormCollapsed]);

  const handleExport = React.useCallback(() => {
    exportQuotesToFile(searchParams.personName, quotesState.quotes);
  }, [searchParams.personName, quotesState.quotes]);

  const handleAutoExtract = React.useCallback(async (url: string) => {
    searchParams.setIsExtracting(true);
    setExtractionStatus('Fetching article content...');
    setExtractionError(null);

    try {
      const response = await fetchArticle(url, extractionLanguage);
      const { textContent, metadata, transcript } = response.data;
      searchParams.setTextToExtract(textContent);
      setExtractedSourceUrl(metadata.url);

      if (transcript) {
        setExtractionStatus('Opening transcript viewer...');
        setTimeout(() => {
          uiState.openTranscriptViewer({
            videoId: transcript.videoId,
            languageCode: transcript.languageCode,
            isAutoGenerated: transcript.isAutoGenerated,
            segments: transcript.segments,
          });
        }, 300);
      }
    } catch (error: any) {
      console.error('Auto extraction failed', error);
      setExtractionError(error.response?.data?.message || 'Failed to extract content');
    } finally {
      searchParams.setIsExtracting(false);
      setExtractionStatus('');
    }
  }, [extractionLanguage, searchParams]);

  const handleImport = React.useCallback((event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file) {
      importQuotesFromFile(
        file,
        (data: ExportData) => {
          searchParams.setPersonName(data.personName);
          quotesState.handleLoadQuotes(data);
        },
        (errorMessage: string) => {
          alert(errorMessage);
        }
      );
    }
  }, [quotesState, searchParams]);

  const handleSearch = React.useCallback(() => {
    setResultsTab('new');
    quotesState.handleSearch(
      searchParams.selectedAI,
      searchParams.personName,
      searchParams.selectedLanguages,
      searchParams.resultCount,
      searchParams.temperature,
      searchParams.maxQuoteLength,
      timePeriod.getTimePeriod(),
      quoteFilters.filterCategory,
      quoteFilters.filterRating,
      quoteFilters.sortOrder,
      searchParams.isAgentic,
      searchParams.agenticMode
    );
  }, [quotesState, searchParams, timePeriod, quoteFilters]);

  const handleAnalyzeQuote = React.useCallback((quote: any) => {
    quotesState.handleAnalyzeQuote(quote, searchParams.selectedAI);
  }, [quotesState, searchParams.selectedAI]);

  const handleImproveQuote = React.useCallback((quote: any) => {
    quotesState.handleImproveQuote(quote, searchParams.selectedAI, searchParams.personName);
  }, [quotesState, searchParams.selectedAI, searchParams.personName]);

  const performExtraction = React.useCallback(async (details: any) => {
    searchParams.setIsExtracting(true);
    await quotesState.handleExtractQuotes(searchParams.selectedAI, searchParams.personName, searchParams.textToExtract, details, () => {
      searchParams.clearTextToExtract();
      searchParams.setIsExtracting(false);
    });
    searchParams.setIsExtracting(false);
  }, [quotesState, searchParams]);

  const handleExtractFromUrl = React.useCallback(async () => {
    searchParams.setIsExtracting(true);
    setExtractionStatus('Fetching article...');
    setResultsTab('new');

    try {
      const response = await fetchArticle(searchParams.textToExtract.trim(), extractionLanguage);
      const { transcript } = response.data;

      await quotesState.handleExtractFromUrl(
        searchParams.selectedAI,
        searchParams.personName,
        searchParams.textToExtract.trim(),
        searchParams.temperature,
        (status: string) => setExtractionStatus(status),
        () => {
          searchParams.clearTextToExtract();
        }
      );

      if (transcript) {
        setExtractionStatus('Opening transcript viewer...');
        setTimeout(() => {
          uiState.openTranscriptViewer({
            videoId: transcript.videoId,
            languageCode: transcript.languageCode,
            isAutoGenerated: transcript.isAutoGenerated,
            segments: transcript.segments,
          });
        }, 300);
      }
    } catch (error: any) {
      console.error('Extract from URL error:', error);
      setExtractionError(error.response?.data?.message || 'Failed to extract from URL');
    } finally {
      searchParams.setIsExtracting(false);
      setExtractionStatus('');
    }
  }, [quotesState, searchParams, extractionLanguage]);

  const handleModalSave = React.useCallback((details: any) => {
    if (modalMode === 'extract') {
      performExtraction(details);
    } else {
      quotesState.handleAddQuoteManually(searchParams.personName, searchParams.textToExtract, details, (quote) => {
        if (shouldAnalyzeImmediately) {
          quotesState.handleAnalyzeQuote(quote, searchParams.selectedAI);
        }
      });
      searchParams.clearTextToExtract();
      setExtractedSourceUrl('');
    }
    uiState.closeAddModal();
  }, [modalMode, performExtraction, quotesState, searchParams, shouldAnalyzeImmediately, uiState]);

  const openExtractModal = React.useCallback(() => {
    setModalMode('extract');
    uiState.openAddModal();
  }, [uiState]);

  const openAddQuoteModal = React.useCallback((analyzeImmediately: boolean) => {
    setModalMode('add');
    setShouldAnalyzeImmediately(analyzeImmediately);
    uiState.openAddModal();
  }, [uiState]);

  const handleFetchYoutubeTranscript = React.useCallback(async (videoUrl: string) => {
    searchParams.setIsExtracting(true);
    setExtractionStatus('Fetching YouTube transcript...');
    setExtractionError(null);
    setAutoFetchError(null);

    try {
      const response = await fetch('/api/quotes/fetch-transcript', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ url: videoUrl, save: true }),
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error || 'Failed to fetch transcript');
      }

      const data = await response.json();
      uiState.openTranscriptViewer({
        videoId: data.videoId,
        languageCode: data.languageCode,
        isAutoGenerated: data.isAutoGenerated,
        segments: data.segments,
        sessionId: data.sessionId,
      });
    } catch (error: any) {
      console.error('YouTube transcript error:', error);
      const errorMessage = error.message || 'Failed to fetch YouTube transcript';
      setExtractionError(errorMessage);
      setAutoFetchError(errorMessage);
      setIsTranscriptMethodSelectorOpen(true);
    } finally {
      searchParams.setIsExtracting(false);
      setExtractionStatus('');
    }
  }, [searchParams]);

  const handleImportTranscript = React.useCallback((transcript: TranscriptData) => {
    uiState.openTranscriptViewer({
      videoId: transcript.videoId,
      languageCode: transcript.languageCode,
      isAutoGenerated: transcript.isAutoGenerated,
      segments: transcript.segments,
    });
  }, [uiState]);

  const handleImportAnalysis = React.useCallback((analysis: FullAnalysisData) => {
    const transcript = {
      videoId: analysis.videoId,
      languageCode: 'en',
      isAutoGenerated: false,
      segments: [],
    } as any;

    uiState.openTranscriptViewer({
      videoId: analysis.videoId,
      languageCode: 'en',
      isAutoGenerated: false,
      segments: [],
      initialSessionData: {
        topicAnalysis: analysis.results,
        speakerAnalysis: analysis.speakerResults,
        dialogAnalysis: analysis.dialogResults,
      }
    });
  }, [uiState]);

  const openChangePasswordModal = React.useCallback(() => {
    setIsChangePasswordModalOpen(true);
  }, []);

  const openEditProfileModal = React.useCallback(() => {
    setIsEditProfileModalOpen(true);
  }, []);

  const handleResumeSession = React.useCallback(async (session: AnalysisSession) => {
    try {
      const response = await getSession(session._id);
      const fullSession: AnalysisSession = response.data;

      if (fullSession.sourceType === 'youtube' && fullSession.transcript) {
        uiState.openTranscriptViewer({
          videoId: fullSession.transcript.videoId,
          languageCode: fullSession.transcript.languageCode,
          isAutoGenerated: fullSession.transcript.isAutoGenerated,
          segments: fullSession.transcript.segments,
          sessionId: fullSession._id,
          initialSessionData: {
            topicAnalysis: fullSession.topicAnalysis,
            speakerAnalysis: fullSession.speakerAnalysis,
            dialogAnalysis: fullSession.dialogAnalysis,
          }
        });
        setResultsTab('transcript');
      }
    } catch (error: any) {
      console.error('Failed to resume session:', error);
      alert('Failed to resume session');
    }
  }, [uiState]);

  const handleEditSource = React.useCallback(async (quote: Quote) => {
    if (!quote.contentAnalysisId) {
      alert('This quote is not linked to a content analysis session.');
      return;
    }

    try {
      const response = await getContentAnalysis(quote.contentAnalysisId);
      const contentAnalysis = response.data;

      const initialSelectedStatements = new Map<string, number>();
      const groupId = quote.metadata?.analysisGroupId || 1;

      if (quote.originIds) {
        const matchedStatements: string[] = [];

        quote.originIds.forEach(originId => {
          const [groupIdFromOrigin, indexStr] = originId.split(':');
          const index = parseInt(indexStr, 10);

          const group = contentAnalysis.dialogAnalysis?.find((g: any) => g.id === groupIdFromOrigin);
          if (group?.analysis?.summaryItems?.[index]) {
            matchedStatements.push(originId);
            initialSelectedStatements.set(originId, groupId);
          } else if (group?.analysis?.summaryItems) {
            const availableIndices = group.analysis.summaryItems.length;
            if (availableIndices > 0) {
              const correctedIndex = Math.min(index % availableIndices, availableIndices - 1);
              const correctedStatementId = `${groupIdFromOrigin}:${correctedIndex}`;
              matchedStatements.push(correctedStatementId);
              initialSelectedStatements.set(correctedStatementId, groupId);
            }
          }
        });

        console.log('[handleEditSource] Statement matching:', {
          originalOriginIds: quote.originIds,
          matchedStatements,
          initialSelectedStatementsSize: initialSelectedStatements.size
        });
      }

      uiState.openTranscriptViewer({
        videoId: contentAnalysis.transcript?.videoId || '',
        languageCode: contentAnalysis.languageCode || 'en',
        isAutoGenerated: contentAnalysis.transcript?.isAutoGenerated || false,
        segments: [],
        initialSessionData: {
          topicAnalysis: contentAnalysis.topicAnalysis,
          speakerAnalysis: contentAnalysis.speakerAnalysis,
          dialogAnalysis: contentAnalysis.dialogAnalysis,
        },
        editQuoteId: quote._id,
        contentAnalysisId: quote.contentAnalysisId,
        initialSelectedStatements,
        lockedGroupId: groupId,
      });

    } catch (error: any) {
      console.error('Failed to load content analysis for editing:', error);
      alert('Failed to load source analysis.');
    }
  }, [uiState]);

  return {
    // Auth
    user,
    loginError,
    googleButtonRef,
    handleLogout,
    loginWithPassword,
    updateUser,

    // Hooks
    searchParams,
    timePeriod,
    quotesState,
    quoteFilters,
    uiState,

    // uiState passthroughs
    isFormCollapsed: uiState.isFormCollapsed,
    toggleFormCollapsed: uiState.toggleFormCollapsed,
    isAddModalOpen: uiState.isAddModalOpen,
    openAddModal: uiState.openAddModal,
    closeAddModal: uiState.closeAddModal,
    transcriptData: uiState.transcriptData,
    updateTranscriptSessionId: uiState.updateTranscriptSessionId,
    openTranscriptViewer: uiState.openTranscriptViewer,
    closeTranscriptViewer: uiState.closeTranscriptViewer,
    isExtracting: searchParams.isExtracting,
    setIsExtracting: searchParams.setIsExtracting,

    // Local UI
    logsVisible,
    setLogsVisible,
    isApiKeyModalOpen,
    setIsApiKeyModalOpen,
    isChangePasswordModalOpen,
    setIsChangePasswordModalOpen,
    isEditProfileModalOpen,
    setIsEditProfileModalOpen,
    modalMode,
    setModalMode,
    activeTab,
    setActiveTab,
    resultsTab,
    setResultsTab,
    selectedPerson,
    setSelectedPerson,
    sessionsRefreshTrigger,
    setSessionsRefreshTrigger,
    extractionStatus,
    extractionLanguage,
    setExtractionLanguage,
    extractionError,
    setExtractionError,
    extractedSourceUrl,
    setExtractedSourceUrl,
    shouldAnalyzeImmediately,
    setShouldAnalyzeImmediately,
    isUsageStatsDashboardOpen,
    setIsUsageStatsDashboardOpen,
    isAdminBannerCollapsed,
    setIsAdminBannerCollapsed,
    isTranscriptMethodSelectorOpen,
    setIsTranscriptMethodSelectorOpen,
    autoFetchError,
    setAutoFetchError,

    // Actions
    handleExport,
    handleAutoExtract,
    handleImport,
    handleSearch,
    handleAnalyzeQuote,
    handleImproveQuote,
    performExtraction,
    handleExtractFromUrl,
    handleModalSave,
    openExtractModal,
    openAddQuoteModal,
    handleFetchYoutubeTranscript,
    handleImportTranscript,
    handleImportAnalysis,
    openChangePasswordModal,
    openEditProfileModal,
    handleResumeSession,
    handleEditSource,

    // helpers
    handleSaveQuote: async (quote: any) => {
      return saveQuote(quote);
    }
  };
}
