import { useState, useRef, useEffect } from 'react';
import { useTranscriptAnalysis } from './useTranscriptAnalysis';
import { useSearchParams } from './useSearchParams';
import { downloadTranscriptJson, downloadTranscriptText, TranscriptData } from '../utils/transcriptStorage';
import { downloadSpeakerAnalysisJson, parseSpeakerAnalysisFromJson } from '../utils/speakerStorage';
import { downloadAnalysisJson, parseAnalysisFromJson, FullAnalysisData } from '../utils/analysisStorage';
import { createSession, updateSessionStep } from '../utils/api';
import { TranscriptSegment, parseTimestamp, constructFormattedTranscript } from '../utils/transcriptHelpers';

export interface UseTranscriptViewerProps {
  segments: TranscriptSegment[];
  videoId: string;
  languageCode: string;
  isAutoGenerated: boolean;
  sessionId?: string;
  initialSessionData?: {
    topicAnalysis?: any[];
    speakerAnalysis?: any[];
    dialogAnalysis?: any[];
  };
  onSessionCreated?: (sessionId: string) => void;
  initialSelectedStatements?: Map<string, number>;
  lockedGroupId?: number;
  editQuoteId?: string;
  contentAnalysisId?: string;
}

export const useTranscriptViewer = ({
  segments,
  videoId,
  languageCode,
  isAutoGenerated,
  sessionId,
  initialSessionData,
  onSessionCreated,
  initialSelectedStatements,
  lockedGroupId,
  editQuoteId,
  contentAnalysisId,
}: UseTranscriptViewerProps) => {
  const [viewMode, setViewMode] = useState<'transcript' | 'topics' | 'speakers' | 'dialog'>(() => {
    // If we have initial selected statements (edit mode), start in dialog view
    if (initialSelectedStatements && initialSelectedStatements.size > 0) return 'dialog';
    if (initialSessionData?.dialogAnalysis && initialSessionData.dialogAnalysis.length > 0) return 'dialog';
    if (initialSessionData?.speakerAnalysis && initialSessionData.speakerAnalysis.length > 0) return 'speakers';
    if (initialSessionData?.topicAnalysis && initialSessionData.topicAnalysis.length > 0) return 'topics';
    return 'transcript';
  });
  const [searchTerm, setSearchTerm] = useState<string>('');
  const [filteredSegments, setFilteredSegments] = useState<TranscriptSegment[]>(segments);
  const [expandedBlocks, setExpandedBlocks] = useState<Set<string>>(new Set());
  const [highlightedDialogLineId, setHighlightedDialogLineId] = useState<string | null>(null);
  const [currentSessionId, setCurrentSessionId] = useState<string | undefined>(sessionId);
  const [isCreatingSession, setIsCreatingSession] = useState(false);
  
  // Selection state for promotion
  const [selectedStatements, setSelectedStatements] = useState<Map<string, number>>(initialSelectedStatements || new Map());
  // If we have initial selected statements (edit mode), automatically enable selection mode
  const [isSelectionMode, setIsSelectionMode] = useState(!!initialSelectedStatements && initialSelectedStatements.size > 0);
  const [lastUsedGroupId, setLastUsedGroupId] = useState(lockedGroupId || 1);
  const [selectedLanguage, setSelectedLanguage] = useState<string>(languageCode || 'en');

  const segmentRefs = useRef<(HTMLDivElement | null)[]>([]);
  const dialogLineRefs = useRef<Map<string, HTMLDivElement>>(new Map());
  const fileInputRef = useRef<HTMLInputElement>(null);
  const fullAnalysisInputRef = useRef<HTMLInputElement>(null);
  
  // Get API key info from search params
  const { selectedAI } = useSearchParams();
  
  // Topic analysis hook
  const topicAnalysis = useTranscriptAnalysis(initialSessionData);

  const formattedText = constructFormattedTranscript(segments);

  // Ensure selection mode is enabled when we have initial selected statements
  useEffect(() => {
    if (initialSelectedStatements && initialSelectedStatements.size > 0) {
      setSelectedStatements(new Map(initialSelectedStatements));
      setIsSelectionMode(true);
    }
  }, [initialSelectedStatements]);

  const handleToggleSelection = (statementId: string, _groupId: number) => {
    const newMap = new Map(selectedStatements);
    if (newMap.has(statementId)) {
      newMap.delete(statementId);
    } else {
      newMap.set(statementId, lockedGroupId || lastUsedGroupId);
    }
    setSelectedStatements(newMap);
  };

  const handleGroupChange = (statementId: string, newGroupId: number) => {
    if (lockedGroupId) return;
    const newMap = new Map(selectedStatements);
    if (newMap.has(statementId)) {
      newMap.set(statementId, newGroupId);
      setSelectedStatements(newMap);
      setLastUsedGroupId(newGroupId);
    }
  };

  /**
   * Ensure a session exists and transcript is saved before analysis
   * Auto-creates session if needed
   */
  const ensureSession = async (): Promise<string | undefined> => {
    if (currentSessionId) {
      return currentSessionId;
    }

    if (isCreatingSession) {
      // Wait for session creation to complete
      return new Promise(resolve => {
        const checkInterval = setInterval(() => {
          if (currentSessionId) {
            clearInterval(checkInterval);
            resolve(currentSessionId);
          }
        }, 100);
        // Timeout after 5 seconds
        setTimeout(() => {
          clearInterval(checkInterval);
          resolve(undefined);
        }, 5000);
      });
    }

    setIsCreatingSession(true);
    try {
      const response = await createSession(`https://www.youtube.com/watch?v=${videoId}`, 'youtube');
      const newSessionId = response.data._id;
      
      // Save the transcript to the session
      await updateSessionStep(newSessionId, 'transcript', {
        videoId,
        languageCode,
        isAutoGenerated,
        segments
      }, 'extracting_transcript');
      
      setCurrentSessionId(newSessionId);
      if (onSessionCreated) {
        onSessionCreated(newSessionId);
      }
      return newSessionId;
    } catch (error) {
      console.error('Failed to auto-create session:', error);
      return undefined;
    } finally {
      setIsCreatingSession(false);
    }
  };

  // Filter segments based on search term
  useEffect(() => {
    if (!searchTerm.trim()) {
      setFilteredSegments(segments);
      return;
    }

    const filtered = segments.filter(segment =>
      segment.text.toLowerCase().includes(searchTerm.toLowerCase())
    );
    setFilteredSegments(filtered);
  }, [searchTerm, segments]);

  const handleCopyText = () => {
    navigator.clipboard.writeText(formattedText);
  };

  const handleDownloadTranscript = () => {
    downloadTranscriptText(segments, videoId);
  };

  const handleDownloadJSON = () => {
    const transcriptData: TranscriptData = {
      videoId,
      languageCode,
      isAutoGenerated,
      segments,
    };
    downloadTranscriptJson(transcriptData, videoId);
  };

  const handleSegmentClick = (start: number) => {
    const url = `https://www.youtube.com/watch?v=${videoId}&t=${Math.floor(start)}s`;
    window.open(url, '_blank');
  };

  const handleAnalyzeTopics = async () => {
    // Get API keys from localStorage
    const apiKeys: Record<string, string> = {};
    try {
      const stored = localStorage.getItem('apiKeys');
      if (stored) {
        const parsed = JSON.parse(stored);
        Object.assign(apiKeys, parsed);
      }
    } catch (e) {
      console.error('Failed to load API keys from localStorage', e);
    }

    // Ensure a session exists before analyzing
    const sId = await ensureSession();

    await topicAnalysis.analyzeTranscript(
      segments,
      languageCode,
      selectedAI || 'gemini',
      apiKeys,
      sId
    );
    setViewMode('topics');
  };

  const handleAnalyzeSpeakers = async () => {
    // Get API keys from localStorage
    const apiKeys: Record<string, string> = {};
    try {
      const stored = localStorage.getItem('apiKeys');
      if (stored) {
        const parsed = JSON.parse(stored);
        Object.assign(apiKeys, parsed);
      }
    } catch (e) {
      console.error('Failed to load API keys from localStorage', e);
    }

    // Ensure a session exists before analyzing
    const sId = await ensureSession();

    await topicAnalysis.analyzeSpeakers(
      languageCode,
      selectedAI || 'gemini',
      apiKeys,
      sId
    );
    setViewMode('speakers');
  };

  const handleAnalyzeDialog = async (overrideLanguage?: string) => {
    if (overrideLanguage) {
      setSelectedLanguage(overrideLanguage);
    }

    // Get API keys from localStorage
    const apiKeys: Record<string, string> = {};
    try {
      const stored = localStorage.getItem('apiKeys');
      if (stored) {
        const parsed = JSON.parse(stored);
        Object.assign(apiKeys, parsed);
      }
    } catch (e) {
      console.error('Failed to load API keys from localStorage', e);
    }

    // Ensure a session exists before analyzing
    const sId = await ensureSession();

    await topicAnalysis.analyzeDialog(
      overrideLanguage || languageCode,
      'gemini-2.0-flash-exp', // Fast model
      'gemini-2.5-flash',       // Better model
      apiKeys,
      sId
    );
    setViewMode('dialog');
  };

  const toggleBlockExpand = (blockId: string) => {
    const newExpanded = new Set(expandedBlocks);
    if (newExpanded.has(blockId)) {
      newExpanded.delete(blockId);
    } else {
      newExpanded.add(blockId);
    }
    setExpandedBlocks(newExpanded);
  };

  /**
   * Handle clicking on a summary item to highlight and scroll to matching dialog
   */
  const handleSummaryItemClick = (groupId: string, timestamp: string, groupDialogLines: any[]) => {
    const targetSeconds = parseTimestamp(timestamp);
    if (targetSeconds === null) return;

    // Find the closest dialog line by timestamp
    let closestLine = groupDialogLines[0];
    let closestDiff = Math.abs(closestLine.timestamp - targetSeconds);

    for (const line of groupDialogLines) {
      const diff = Math.abs(line.timestamp - targetSeconds);
      if (diff < closestDiff) {
        closestDiff = diff;
        closestLine = line;
      }
    }

    // Create unique ID for this dialog line
    const lineId = `${groupId}-${groupDialogLines.indexOf(closestLine)}-${closestLine.timestamp}`;
    setHighlightedDialogLineId(lineId);

    // Scroll to the dialog line
    const element = dialogLineRefs.current.get(lineId);
    if (element) {
      element.scrollIntoView({
        behavior: 'smooth',
        block: 'nearest',
      });
    }

    // Clear highlight after 3 seconds
    setTimeout(() => {
      setHighlightedDialogLineId(null);
    }, 3000);
  };

  const handleExportSpeakers = () => {
    if (topicAnalysis.speakerResults.length > 0) {
      downloadSpeakerAnalysisJson(topicAnalysis.speakerResults, videoId);
    }
  };

  const handleImportSpeakersClick = () => {
    fileInputRef.current?.click();
  };

  const handleExportAnalysis = () => {
    const data: FullAnalysisData = {
      version: 1,
      timestamp: new Date().toISOString(),
      videoId,
      results: topicAnalysis.results,
      speakerResults: topicAnalysis.speakerResults,
      dialogResults: topicAnalysis.dialogResults,
    };
    downloadAnalysisJson(data, `analysis_${videoId}`);
  };

  const handleImportAnalysisClick = () => {
    fullAnalysisInputRef.current?.click();
  };

  const handleFullAnalysisFileChange = async (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;

    try {
      const data = await parseAnalysisFromJson(file);
      topicAnalysis.setFullAnalysisState(
        data.results || [],
        data.speakerResults || [],
        data.dialogResults || []
      );
      
      // Switch to the most advanced view available
      if (data.dialogResults && data.dialogResults.length > 0) {
        setViewMode('dialog');
      } else if (data.speakerResults && data.speakerResults.length > 0) {
        setViewMode('speakers');
      } else if (data.results && data.results.length > 0) {
        setViewMode('topics');
      }
      
    } catch (error) {
      console.error('Failed to import analysis:', error);
      alert('Failed to import analysis file. Please check the file format.');
    }
    
    // Reset input
    event.target.value = '';
  };

  const handleFileChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (e) => {
      try {
        const content = e.target?.result as string;
        const results = parseSpeakerAnalysisFromJson(content);
        topicAnalysis.setSpeakerResults(results);
        setViewMode('speakers');
      } catch (error) {
        console.error('Failed to import speaker analysis:', error);
        alert('Failed to import speaker analysis file. Please check the file format.');
      }
    };
    reader.readAsText(file);
    // Reset input
    event.target.value = '';
  };

  const handleSaveSession = async () => {
    if (currentSessionId) return;
    
    try {
      const response = await createSession(`https://www.youtube.com/watch?v=${videoId}`, 'youtube');
      const newSessionId = response.data._id;
      
      try {
        // Save the transcript to the session
        await updateSessionStep(newSessionId, 'transcript', {
          videoId,
          languageCode,
          isAutoGenerated,
          segments
        }, 'extracting_transcript');
        
        // Save topic analysis if available
        if (topicAnalysis.results.length > 0) {
          await updateSessionStep(newSessionId, 'topicAnalysis', topicAnalysis.results, 'analyzing_topics');
        }
        
        // Save speaker analysis if available
        if (topicAnalysis.speakerResults.length > 0) {
          await updateSessionStep(newSessionId, 'speakerAnalysis', topicAnalysis.speakerResults, 'identifying_speakers');
        }
        
        // Save dialog analysis if available (mark as completed)
        if (topicAnalysis.dialogResults.length > 0) {
          await updateSessionStep(newSessionId, 'dialogAnalysis', topicAnalysis.dialogResults, 'completed');
        } else if (topicAnalysis.speakerResults.length > 0) {
          // If only speaker analysis is available, mark as identifying_speakers
          // Do nothing as we already saved it above
        } else if (topicAnalysis.results.length > 0) {
          // If only topic analysis is available, mark as analyzing_topics
          // Do nothing as we already saved it above
        }
        
        setCurrentSessionId(newSessionId);
        if (onSessionCreated) {
          onSessionCreated(newSessionId);
        }
      } catch (updateError) {
        console.error('Failed to save session data:', updateError);
        alert('Failed to save all data to database. Session created but some data may not be saved.');
      }
    } catch (error) {
        console.error('Failed to create session:', error);
      alert('Failed to save session to database.');
    }
  };

  // Build step statuses for step progress bar
  const getStepStatuses = () => {
    const steps = [
      {
        step: 'transcript' as const,
        status: segments.length > 0 ? 'completed' as const : 'pending' as const,
        resultCount: segments.length,
        label: 'Transcription',
      },
      {
        step: 'topics' as const,
        status: topicAnalysis.isAnalyzing 
          ? 'processing' as const 
          : topicAnalysis.error && topicAnalysis.results.length === 0
            ? 'error' as const
            : topicAnalysis.results.length > 0 
              ? 'completed' as const 
              : 'pending' as const,
        resultCount: topicAnalysis.results.length,
        label: 'Groups',
      },
      {
        step: 'speakers' as const,
        status: topicAnalysis.isSpeakerAnalyzing 
          ? 'processing' as const 
          : topicAnalysis.error && topicAnalysis.speakerResults.length === 0 && topicAnalysis.results.length > 0
            ? 'error' as const
            : topicAnalysis.speakerResults.length > 0 
              ? 'completed' as const 
              : 'pending' as const,
        resultCount: topicAnalysis.speakerResults.length,
        label: 'Speakers',
      },
      {
        step: 'dialog' as const,
        status: topicAnalysis.isDialogAnalyzing 
          ? 'processing' as const 
          : topicAnalysis.error && topicAnalysis.dialogResults.length === 0 && topicAnalysis.speakerResults.length > 0
            ? 'error' as const
            : topicAnalysis.dialogResults.length > 0 
              ? 'completed' as const 
              : 'pending' as const,
        resultCount: topicAnalysis.dialogResults.length,
        label: 'Statements',
      },
    ];
    return steps;
  };

  // Speaker editing handlers with auto-save
  const saveSpeakerResults = async (results: any[]) => {
    if (!currentSessionId) return;
    try {
      await updateSessionStep(currentSessionId, 'speakerAnalysis', results, 'identifying_speakers');
    } catch (error) {
      console.error('Failed to save speaker results:', error);
    }
  };

  const handleRenameSpeaker = async (speakerId: string, newName: string) => {
    if (!newName.trim()) return;
    const updatedResults = topicAnalysis.renameSpeaker(speakerId, newName.trim());
    await saveSpeakerResults(updatedResults);
  };

  /**
   * Check for similar existing persons before adding a new speaker.
   * Returns matches for user confirmation, or empty array if no matches.
   */
  const checkSimilarPersonsBeforeAdd = async (speakerName: string) => {
    if (!speakerName.trim()) return [];
    return topicAnalysis.checkSimilarPersonsForSpeaker(speakerName.trim());
  };

  /**
   * Add a speaker, optionally using an existing person if confirmed by user.
   * @param speakerName The speaker name to add
   * @param existingPerson Optional existing person to use instead of creating new
   */
  const handleAddSpeaker = async (
    speakerName: string, 
    existingPerson?: { personId: string; name: string }
  ) => {
    if (!speakerName.trim()) return;
    const updatedResults = topicAnalysis.addSpeaker(speakerName.trim(), existingPerson);
    await saveSpeakerResults(updatedResults);
  };

  const handleRemoveSpeaker = async (speakerId: string): Promise<boolean> => {
    const updatedResults = topicAnalysis.removeSpeaker(speakerId);
    if (updatedResults === null) {
      return false; // Speaker is in use, cannot remove
    }
    await saveSpeakerResults(updatedResults);
    return true;
  };

  const handleUpdateLineSpeaker = async (blockId: string, lineId: string, newSpeakerId: string) => {
    const updatedResults = topicAnalysis.updateLineSpeaker(blockId, lineId, newSpeakerId);
    await saveSpeakerResults(updatedResults);
  };

  const handleMergeSpeakers = async (speakerIdsToMerge: string[], targetSpeakerId: string): Promise<boolean> => {
    if (!currentSessionId) return false;
    const result = await topicAnalysis.mergeSpeakers(speakerIdsToMerge, targetSpeakerId, currentSessionId);
    return result !== null;
  };

  /**
   * Link a speaker to an existing Person record
   */
  const handleLinkSpeakerToPerson = async (speakerId: string, personId: string, personName: string) => {
    const updatedResults = topicAnalysis.linkSpeakerToPerson(speakerId, personId, personName);
    await saveSpeakerResults(updatedResults);
  };

  /**
   * Unlink a speaker from its Person record
   */
  const handleUnlinkSpeakerFromPerson = async (speakerId: string) => {
    const updatedResults = topicAnalysis.unlinkSpeakerFromPerson(speakerId);
    await saveSpeakerResults(updatedResults);
  };

  return {
    viewMode,
    setViewMode,
    searchTerm,
    setSearchTerm,
    filteredSegments,
    expandedBlocks,
    highlightedDialogLineId,
    currentSessionId,
    isCreatingSession,
    segmentRefs,
    dialogLineRefs,
    fileInputRef,
    fullAnalysisInputRef,
    topicAnalysis,
    handleCopyText,
    handleDownloadTranscript,
    handleDownloadJSON,
    handleSegmentClick,
    handleAnalyzeTopics,
    handleAnalyzeSpeakers,
    handleAnalyzeDialog,
    toggleBlockExpand,
    handleSummaryItemClick,
    handleExportSpeakers,
    handleImportSpeakersClick,
    handleExportAnalysis,
    handleImportAnalysisClick,
    handleFullAnalysisFileChange,
    handleFileChange,
    handleSaveSession,
    selectedStatements,
    isSelectionMode,
    setIsSelectionMode,
    handleToggleSelection,
    handleGroupChange,
    selectedLanguage,
    setSelectedLanguage,
    contentAnalysisId,
    editQuoteId,
    getStepStatuses,
    handleRenameSpeaker,
    handleAddSpeaker,
    checkSimilarPersonsBeforeAdd,
    handleRemoveSpeaker,
    handleUpdateLineSpeaker,
    handleMergeSpeakers,
    handleLinkSpeakerToPerson,
    handleUnlinkSpeakerFromPerson,
    handleStartStep: (step: 'transcript' | 'topics' | 'speakers' | 'dialog') => {
      switch (step) {
        case 'topics':
          handleAnalyzeTopics();
          break;
        case 'speakers':
          handleAnalyzeSpeakers();
          break;
        case 'dialog':
          handleAnalyzeDialog();
          break;
      }
    },
  };
};
