import { useState, useCallback } from 'react';
import { ExportData } from '../types';

export interface TranscriptSegment {
  start: number;
  duration: number;
  text: string;
}

export interface TranscriptData {
  videoId: string;
  languageCode: string;
  isAutoGenerated: boolean;
  segments: TranscriptSegment[];
  sessionId?: string;
  initialSessionData?: {
    topicAnalysis?: any[];
    speakerAnalysis?: any[];
    dialogAnalysis?: any[];
  };
  editQuoteId?: string;
  contentAnalysisId?: string;
  initialSelectedStatements?: Map<string, number>;
  lockedGroupId?: number;
}

export function useUIState() {
  const [isFormCollapsed, setIsFormCollapsed] = useState<boolean>(false);
  const [isAddModalOpen, setIsAddModalOpen] = useState<boolean>(false);
  const [isTranscriptViewerOpen, setIsTranscriptViewerOpen] = useState<boolean>(false);
  const [transcriptData, setTranscriptData] = useState<TranscriptData | null>(null);

  const [isImportQuoteModalOpen, setIsImportQuoteModalOpen] = useState<boolean>(false);
  const [importQuoteData, setImportQuoteData] = useState<ExportData | null>(null);

  const toggleFormCollapsed = useCallback(() => {
    setIsFormCollapsed((prev) => !prev);
  }, []);

  const openAddModal = useCallback(() => {
    setIsAddModalOpen(true);
  }, []);

  const closeAddModal = useCallback(() => {
    setIsAddModalOpen(false);
  }, []);

  const openTranscriptViewer = useCallback((data: TranscriptData) => {
    setTranscriptData(data);
    setIsTranscriptViewerOpen(true);
  }, []);

  const closeTranscriptViewer = useCallback(() => {
    setIsTranscriptViewerOpen(false);
    setTranscriptData(null);
  }, []);

  const updateTranscriptSessionId = useCallback((sessionId: string) => {
    setTranscriptData(prev => prev ? { ...prev, sessionId } : null);
  }, []);

  const openImportQuoteModal = useCallback((data: ExportData) => {
    setImportQuoteData(data);
    setIsImportQuoteModalOpen(true);
  }, []);

  const closeImportQuoteModal = useCallback(() => {
    setIsImportQuoteModalOpen(false);
    setImportQuoteData(null);
  }, []);

  return {
    isFormCollapsed,
    setIsFormCollapsed,
    toggleFormCollapsed,
    isAddModalOpen,
    openAddModal,
    closeAddModal,
    isTranscriptViewerOpen,
    transcriptData,
    openTranscriptViewer,
    closeTranscriptViewer,
    updateTranscriptSessionId,
    isImportQuoteModalOpen,
    importQuoteData,
    openImportQuoteModal,
    closeImportQuoteModal,
  };
}
