import { useState, useCallback } from 'react';

export interface TranscriptSegment {
  start: number;
  duration: number;
  text: string;
}

export interface TranscriptData {
  videoId: string;
  languageCode: string;
  isAutoGenerated: boolean;
  segments: TranscriptSegment[];
}

export function useUIState() {
  const [isFormCollapsed, setIsFormCollapsed] = useState<boolean>(false);
  const [isAddModalOpen, setIsAddModalOpen] = useState<boolean>(false);
  const [isTranscriptViewerOpen, setIsTranscriptViewerOpen] = useState<boolean>(false);
  const [transcriptData, setTranscriptData] = useState<TranscriptData | null>(null);

  const toggleFormCollapsed = useCallback(() => {
    setIsFormCollapsed((prev) => !prev);
  }, []);

  const openAddModal = useCallback(() => {
    setIsAddModalOpen(true);
  }, []);

  const closeAddModal = useCallback(() => {
    setIsAddModalOpen(false);
  }, []);

  const openTranscriptViewer = useCallback((data: TranscriptData) => {
    setTranscriptData(data);
    setIsTranscriptViewerOpen(true);
  }, []);

  const closeTranscriptViewer = useCallback(() => {
    setIsTranscriptViewerOpen(false);
    setTranscriptData(null);
  }, []);

  return {
    isFormCollapsed,
    setIsFormCollapsed,
    toggleFormCollapsed,
    isAddModalOpen,
    openAddModal,
    closeAddModal,
    isTranscriptViewerOpen,
    transcriptData,
    openTranscriptViewer,
    closeTranscriptViewer,
  };
}
