import React from 'react';
import { X, Check } from 'lucide-react';

interface TranscriptViewHeaderProps {
  videoId: string;
  languageCode: string;
  isAutoGenerated: boolean;
  currentSessionId: string | undefined;
  isCreatingSession: boolean;
  onClose: () => void;
  onSaveSession: () => void;
}

export const TranscriptViewHeader: React.FC<TranscriptViewHeaderProps> = ({
  videoId,
  languageCode,
  isAutoGenerated,
  currentSessionId,
  isCreatingSession,
  onClose,
  onSaveSession,
}) => {
  return (
    <div className="flex justify-between items-center p-6 border-b border-gray-700 flex-shrink-0">
      <div className="flex-1">
        <h2 className="text-2xl font-bold text-white">YouTube Transcript</h2>
        <div className="mt-2 flex gap-4 text-sm text-gray-400">
          <span>
            Video ID: <span className="text-gray-300 font-mono">{videoId}</span>
          </span>
          <span>
            Language: <span className="text-gray-300">{languageCode}</span>
          </span>
          {isAutoGenerated && (
            <span className="text-amber-400 flex items-center gap-1">
              ⚠️ Auto-generated captions
            </span>
          )}
          {currentSessionId ? (
            <span className="text-green-400 flex items-center gap-1 ml-4">
              <Check size={14} /> Saved to DB
            </span>
          ) : (
            <button
              onClick={onSaveSession}
              disabled={isCreatingSession}
              className="ml-4 px-3 py-1 bg-cyan-600/20 hover:bg-cyan-600/40 text-cyan-400 rounded text-xs border border-cyan-600/50 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
            >
              Save to DB
            </button>
          )}
        </div>
      </div>
      <button
        onClick={onClose}
        className="text-gray-400 hover:text-white transition-colors p-2 hover:bg-gray-800 rounded-lg"
        title="Close"
      >
        <X size={24} />
      </button>
    </div>
  );
};

export default TranscriptViewHeader;
