import React, { useState, useMemo, useRef, useEffect } from 'react';
import { 
  Bookmark, 
  AlertCircle, 
  CheckCircle, 
  Copy, 
  ExternalLink,
  MousePointer,
  Youtube
} from 'lucide-react';
import { generateBookmarkletUrl } from '../utils/bookmarklet';
import { parseTranscriptFromJson, TranscriptData } from '../utils/transcriptStorage';

interface BookmarkletImporterProps {
  onImport: (transcript: TranscriptData) => void;
  isLoading?: boolean;
}

export const BookmarkletImporter: React.FC<BookmarkletImporterProps> = ({
  onImport,
  isLoading = false,
}) => {
  const [pastedJson, setPastedJson] = useState('');
  const [error, setError] = useState<string | null>(null);
  const [showInstructions, setShowInstructions] = useState(true);
  const [copied, setCopied] = useState(false);
  const bookmarkletRef = useRef<HTMLAnchorElement>(null);

  const bookmarkletUrl = useMemo(() => generateBookmarkletUrl(), []);

  // Use native DOM to set href, bypassing React's javascript: URL sanitization
  useEffect(() => {
    if (bookmarkletRef.current) {
      bookmarkletRef.current.setAttribute('href', bookmarkletUrl);
    }
  }, [bookmarkletUrl]);

  const handleCopyBookmarklet = async () => {
    try {
      await navigator.clipboard.writeText(bookmarkletUrl);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      // Fallback
      const textArea = document.createElement('textarea');
      textArea.value = bookmarkletUrl;
      document.body.appendChild(textArea);
      textArea.select();
      document.execCommand('copy');
      document.body.removeChild(textArea);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handlePaste = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    const content = e.target.value;
    setPastedJson(content);
    setError(null);
  };

  const handleImport = () => {
    if (!pastedJson.trim()) {
      setError('Please paste the JSON copied from the bookmarklet');
      return;
    }

    try {
      // Try to parse as our bookmarklet format first
      const data = JSON.parse(pastedJson);
      
      if (data.segments && Array.isArray(data.segments)) {
        const transcript: TranscriptData = {
          videoId: data.videoId || 'imported',
          languageCode: data.languageCode || 'unknown',
          isAutoGenerated: data.isAutoGenerated || false,
          segments: data.segments,
        };
        onImport(transcript);
        setPastedJson('');
        return;
      }
      
      // Try standard transcript format
      const transcript = parseTranscriptFromJson(pastedJson);
      onImport(transcript);
      setPastedJson('');
    } catch (err: any) {
      setError('Invalid JSON format. Make sure you copied the complete output from the bookmarklet.');
    }
  };

  return (
    <div className="p-4 bg-gray-800/50 rounded-lg border border-gray-700 space-y-4">
      <div className="flex items-center justify-between">
        <h2 className="text-xl font-semibold text-cyan-400 flex items-center gap-2">
          <Bookmark size={20} />
          Bookmarklet Method
        </h2>
      </div>

      <p className="text-sm text-gray-400">
        Use our bookmarklet to extract transcripts directly from YouTube with one click
      </p>

      {/* Bookmarklet Installation */}
      {showInstructions && (
        <div className="p-4 bg-gradient-to-r from-cyan-900/30 to-purple-900/30 rounded-lg border border-cyan-700/50 space-y-4">
          <h3 className="font-medium text-cyan-300 flex items-center gap-2">
            <MousePointer size={16} />
            Step 1: Install the Bookmarklet
          </h3>
          
          <div className="space-y-3">
            {/* Method A: Drag to bookmarks bar */}
            <div className="flex items-center gap-4">
              <div className="flex-shrink-0">
                {/* Draggable Bookmarklet Button - using ref to bypass React's sanitization */}
                <a
                  ref={bookmarkletRef}
                  href="#"
                  onClick={(e) => e.preventDefault()}
                  draggable
                  className="inline-flex items-center gap-2 px-4 py-2 bg-gradient-to-r from-red-600 to-red-700 hover:from-red-500 hover:to-red-600 text-white font-semibold rounded-lg shadow-lg cursor-grab active:cursor-grabbing border border-red-500"
                  title="Drag this button to your bookmarks bar"
                >
                  <Youtube size={18} />
                  Get YT Transcript
                </a>
              </div>
              <div className="text-sm text-gray-300">
                <p className="flex items-center gap-1">
                  <span className="text-cyan-400">←</span> 
                  Drag this button to your bookmarks bar
                </p>
              </div>
            </div>

            {/* Method B: Manual installation */}
            <div className="p-3 bg-gray-800 rounded-lg border border-gray-600">
              <p className="text-xs text-gray-400 mb-2">
                <strong>Alternative:</strong> If dragging doesn't work, create a bookmark manually:
              </p>
              <ol className="text-xs text-gray-400 space-y-1 list-decimal list-inside mb-3">
                <li>Click the button below to copy the bookmarklet code</li>
                <li>Create a new bookmark in your browser</li>
                <li>Name it "Get YT Transcript"</li>
                <li>Paste the copied code as the URL</li>
              </ol>
              <button
                onClick={handleCopyBookmarklet}
                className={`w-full px-3 py-2 text-sm font-medium rounded-lg transition-colors flex items-center justify-center gap-2 ${
                  copied
                    ? 'bg-green-600 text-white'
                    : 'bg-gray-700 hover:bg-gray-600 text-gray-200'
                }`}
              >
                <Copy size={14} />
                {copied ? 'Copied!' : 'Copy Bookmarklet Code'}
              </button>
            </div>
          </div>

          <div className="text-xs text-gray-400 space-y-1 border-t border-gray-700 pt-3 mt-3">
            <p className="flex items-center gap-1">
              <CheckCircle size={12} className="text-green-400" />
              Works on any YouTube video with captions
            </p>
            <p className="flex items-center gap-1">
              <CheckCircle size={12} className="text-green-400" />
              Uses your browser session (no server needed)
            </p>
            <p className="flex items-center gap-1">
              <CheckCircle size={12} className="text-green-400" />
              One-click extraction with auto-copy
            </p>
          </div>
        </div>
      )}

      {/* Usage Instructions */}
      <div className="p-4 bg-gray-900/50 rounded-lg border border-gray-600 space-y-3">
        <h3 className="font-medium text-cyan-300 flex items-center gap-2">
          <ExternalLink size={16} />
          Step 2: Use the Bookmarklet
        </h3>
        <ol className="text-sm text-gray-300 space-y-2 list-decimal list-inside">
          <li>Go to any YouTube video page</li>
          <li>Click the <strong className="text-white">"Get YT Transcript"</strong> bookmarklet</li>
          <li>The transcript JSON will be copied to your clipboard</li>
          <li>Paste it in the box below</li>
        </ol>
      </div>

      {/* Paste Area */}
      <div>
        <label className="text-sm font-medium text-gray-300 mb-2 flex items-center justify-between">
          <span>
            Step 3: Paste JSON <span className="text-red-400">*</span>
          </span>
          {pastedJson && (
            <span className="text-xs text-gray-500">
              {pastedJson.length.toLocaleString()} characters
            </span>
          )}
        </label>
        <textarea
          value={pastedJson}
          onChange={handlePaste}
          placeholder='Paste the JSON here (from bookmarklet)...'
          disabled={isLoading}
          rows={6}
          className={`w-full bg-gray-700 text-white border rounded-lg px-4 py-2 focus:outline-none focus:ring-1 disabled:bg-gray-600 disabled:cursor-not-allowed font-mono text-xs ${
            error
              ? 'border-red-500 focus:border-red-500 focus:ring-red-500/50'
              : 'border-gray-600 focus:border-cyan-500 focus:ring-cyan-500/50'
          }`}
        />
      </div>

      {/* Import Button */}
      <button
        onClick={handleImport}
        disabled={isLoading || !pastedJson.trim()}
        className="w-full px-4 py-3 bg-cyan-600 hover:bg-cyan-700 text-white font-semibold rounded-lg transition-colors disabled:bg-gray-600 disabled:cursor-not-allowed flex items-center justify-center gap-2"
      >
        <Copy size={18} />
        {isLoading ? 'Processing...' : 'Import from Bookmarklet'}
      </button>

      {/* Error Message */}
      {error && (
        <div className="flex gap-2 p-3 bg-red-900/30 border border-red-700 rounded-lg text-red-300 text-sm">
          <AlertCircle size={18} className="flex-shrink-0 mt-0.5" />
          <span>{error}</span>
        </div>
      )}

      {/* Toggle Instructions */}
      <button
        onClick={() => setShowInstructions(!showInstructions)}
        className="w-full text-sm text-gray-500 hover:text-gray-300 transition-colors"
      >
        {showInstructions ? 'Hide' : 'Show'} installation instructions
      </button>
    </div>
  );
};

export default BookmarkletImporter;
