import React from 'react';
import StoredQuotes from './StoredQuotes';
import TranscriptViewer from './TranscriptViewer';
import { useI18n } from '../i18n';
import { SearchResults } from './results/SearchResults';

interface MainContentProps {
  activeTab: 'search' | 'people' | 'users' | 'sessions';
  resultsTab: 'new' | 'stored' | 'transcript';
  setResultsTab: (tab: 'new' | 'stored' | 'transcript') => void;
  statusFilters: {
    isAnalyzed: 'all' | 'true' | 'false';
    setIsAnalyzed: (value: 'all' | 'true' | 'false') => void;
    isImproved: 'all' | 'true' | 'false';
    setIsImproved: (value: 'all' | 'true' | 'false') => void;
  };
  transcriptData: any | null;
  selectedPerson: any | null;
  setSelectedPerson: (p: any | null) => void;

  // Quote state
  quotes: any[];
  articles: any[];
  isLoading: boolean;
  error: string | null;
  rawApiResponseError: any;
  filteredAndSortedQuotes: any[];
  sortOrder: any;
  setSortOrder: (s: any) => void;

  // handlers
  onClearQuotes: () => void;
  onAnalyze: (q: any, model: string) => void;
  onImprove: (q: any) => void;
  onSave: (q: any) => void;
  onLanguageChange: (q: any, code: string) => void;
  onAccept: (q: any) => void;
  onDiscard: (q: any) => void;
  onRemove: (q: any) => void;
  clearError: () => void;
  onEditSource: (q: any) => void;
  onResumeSession: (session: any) => void;
  onStoredPromoteSuccess: () => void;
  onExport?: () => void;
  onImport?: (e: React.ChangeEvent<HTMLInputElement>) => void;
  selectedAI: string;
}

export const MainContent: React.FC<MainContentProps> = ({
  activeTab,
  resultsTab,
  setResultsTab,
  statusFilters,
  transcriptData,
  selectedPerson,
  setSelectedPerson,
  quotes,
  articles,
  isLoading,
  error,
  rawApiResponseError,
  filteredAndSortedQuotes,
  sortOrder,
  setSortOrder,
  onClearQuotes,
  onAnalyze,
  onImprove,
  onSave,
  onLanguageChange,
  onAccept,
  onDiscard,
  onRemove,
  clearError,
  onEditSource,
  onResumeSession,
  onStoredPromoteSuccess,
  onExport,
  onImport,
  selectedAI,
}) => {
  const { t } = useI18n();

  return (
    <div className="md:col-span-2 space-y-6 min-w-0 w-full mobile:w-[100vw] mobile:max-w-[100vw] mobile:box-border">
      <>
          <div className="flex space-x-1 mb-4 bg-gray-800 p-1 rounded-lg">
            <button
              onClick={() => setResultsTab('new')}
              className={`flex-1 py-2 text-sm font-medium rounded-md transition-colors ${
                resultsTab === 'new'
                  ? 'bg-cyan-600 text-white shadow'
                  : 'text-gray-400 hover:text-white hover:bg-gray-700'
              }`}
            >
              {t('searchResultsTab')}
            </button>
            <button
              onClick={() => setResultsTab('stored')}
              className={`flex-1 py-2 text-sm font-medium rounded-md transition-colors ${
                resultsTab === 'stored'
                  ? 'bg-cyan-600 text-white shadow'
                  : 'text-gray-400 hover:text-white hover:bg-gray-700'
              }`}
            >
              {t('storedQuotesTab')}
            </button>
            {transcriptData && (
              <button
                onClick={() => setResultsTab('transcript')}
                className={`flex-1 py-2 text-sm font-medium rounded-md transition-colors ${
                  resultsTab === 'transcript'
                    ? 'bg-cyan-600 text-white shadow'
                    : 'text-gray-400 hover:text-white hover:bg-gray-700'
                }`}
              >
                {t('transcriptTab')}
              </button>
            )}
          </div>

          {resultsTab === 'transcript' ? (
            transcriptData && (
              <TranscriptViewer
                segments={transcriptData.segments}
                videoId={transcriptData.videoId}
                languageCode={transcriptData.languageCode}
                isAutoGenerated={transcriptData.isAutoGenerated}
                sessionId={transcriptData.sessionId}
                initialSessionData={transcriptData.initialSessionData}
                editQuoteId={transcriptData.editQuoteId}
                contentAnalysisId={transcriptData.contentAnalysisId}
                initialSelectedStatements={transcriptData.initialSelectedStatements}
                lockedGroupId={transcriptData.lockedGroupId}
                onSessionCreated={transcriptData.onSessionCreated}
                onPromoteSuccess={onStoredPromoteSuccess}
              />
            )
          ) : resultsTab === 'stored' ? (
            <div className="space-y-4">
              {selectedPerson && (
                <div className="p-4 bg-gray-800/50 rounded-lg flex justify-between items-center">
                  <span className="text-gray-300">
                    {t('filteredBy', { name: selectedPerson.name })}
                  </span>
                  <button
                    onClick={() => setSelectedPerson(null)}
                    className="text-sm text-cyan-400 hover:text-cyan-300 hover:underline"
                  >
                    {t('clearFilter')}
                  </button>
                </div>
              )}
              <StoredQuotes
                selectedPerson={selectedPerson}
                selectedAI={selectedAI}
                isApiKeySet={true}
                onEditSource={onEditSource}
              />
            </div>
          ) : (
            articles.length > 0 ? (
              <div className="space-y-4">
                <div className="flex justify-between items-center">
                  <h3 className="text-lg font-semibold text-cyan-400">{t('foundArticles', { count: articles.length })}</h3>
                  <button 
                    onClick={() => onClearQuotes()} // Reusing clear quotes to clear results
                    className="text-sm text-gray-400 hover:text-white"
                  >
                    {t('clearResults')}
                  </button>
                </div>
                {articles.map((article, idx) => (
                  <div key={idx} className="p-4 bg-gray-800 rounded-lg border border-gray-700 hover:border-cyan-500/50 transition-colors">
                    <a href={article.url} target="_blank" rel="noopener noreferrer" className="text-cyan-400 hover:underline font-medium text-lg block mb-2">
                      {article.title}
                    </a>
                    <p className="text-gray-300 text-sm leading-relaxed">{article.summary}</p>
                    <div className="mt-3 flex flex-wrap gap-2">
                      {article.tags.map((tag: string) => (
                        <span key={tag} className="px-2 py-1 bg-gray-700 text-gray-300 text-xs rounded-full border border-gray-600">
                          {tag}
                        </span>
                      ))}
                    </div>
                    <div className="mt-3 flex justify-between items-center text-xs text-gray-500">
                      <span>{t('relevance')}: {(article.relevanceScore * 100).toFixed(0)}%</span>
                      {article.publishedDate && <span>{article.publishedDate}</span>}
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              <SearchResults
                results={filteredAndSortedQuotes}
                error={error}
                rawApiResponseError={rawApiResponseError}
                personName={''}
                sortOrder={sortOrder}
                setSortOrder={setSortOrder}
                onClear={onClearQuotes}
                onAnalyze={onAnalyze}
                onImprove={onImprove}
                onSave={onSave}
                onLanguageChange={onLanguageChange}
                onAccept={onAccept}
                onDiscard={onDiscard}
                onRemove={onRemove}
                clearError={clearError}
                selectedAI={selectedAI}
                statusFilters={statusFilters}
                onExport={onExport}
                onImport={onImport}
              />
            )
          )}
        </>
    </div>
  );
};

export default MainContent;
