import React, { useState, useRef } from 'react';
import { Upload, Play, AlertCircle, FileText } from 'lucide-react';
import { parseSrtContent, extractYouTubeVideoId, isValidYouTubeUrl } from '../utils/srtParser';
import { useI18n } from '../i18n';
import { TranscriptData } from '../utils/transcriptStorage';

interface SrtTranscriptImporterProps {
  onImport: (transcript: TranscriptData) => void;
  isLoading?: boolean;
}

export const SrtTranscriptImporter: React.FC<SrtTranscriptImporterProps> = ({
  onImport,
  isLoading = false,
}) => {
  const [youtubeUrl, setYoutubeUrl] = useState('');
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [urlError, setUrlError] = useState<string | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const { t } = useI18n();

  const handleFileSelected = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      setSelectedFile(file);
      setError(null);
    }
  };

  const handleUrlChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const url = e.target.value;
    setYoutubeUrl(url);
    setUrlError(null);
    
    // Validate URL format as user types
    if (url.trim() && !isValidYouTubeUrl(url)) {
      setUrlError(t('pleaseEnterValidYouTubeUrl'));
    }
  };

  const handleImport = async () => {
    setError(null);
    setUrlError(null);

    // Validate YouTube URL
    if (!youtubeUrl.trim()) {
      setUrlError(t('pleaseEnterYoutubeUrl'));
      return;
    }

    const videoId = extractYouTubeVideoId(youtubeUrl);
    if (!videoId) {
      setUrlError(t('pleaseEnterValidYouTubeUrl'));
      return;
    }

    // Validate SRT file
    if (!selectedFile) {
      setError(t('pleaseSelectSrtFile'));
      return;
    }

    try {
      const content = await selectedFile.text();
      const segments = parseSrtContent(content);

      const transcript: TranscriptData = {
        videoId,
        languageCode: 'unknown', // SRT doesn't contain language info
        isAutoGenerated: false,
        segments,
      };

      onImport(transcript);

      // Reset form
      setYoutubeUrl('');
      setSelectedFile(null);
      if (fileInputRef.current) {
        fileInputRef.current.value = '';
      }
    } catch (err: any) {
      setError(err.message || t('failedToParseSrtFile'));
    }
  };

  const handleKeyPress = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !isLoading && selectedFile && youtubeUrl.trim()) {
      handleImport();
    }
  };

  return (
    <div className="p-4 bg-gray-800/50 rounded-lg border border-gray-700 space-y-4">
      <h2 className="text-lg font-semibold text-cyan-400 mb-3 flex items-center gap-2">
        <FileText size={20} />
        {t('importSrtTranscriptTitle')}
      </h2>

      <p className="text-sm text-gray-400">
        {t('srtImportNote')}
      </p>

      {/* YouTube URL Input */}
      <div>
        <label className="text-sm font-medium text-gray-300 mb-2 block">
          {t('youtubeVideoUrlLabel')}
        </label>
        <input
          type="text"
          value={youtubeUrl}
          onChange={handleUrlChange}
          onKeyPress={handleKeyPress}
          placeholder={t('youtubeUrlPlaceholder')}
          disabled={isLoading}
          className={`w-full bg-gray-700 text-white border rounded-lg px-4 py-2 focus:outline-none focus:ring-1 disabled:bg-gray-600 disabled:cursor-not-allowed ${
            urlError 
              ? 'border-red-500 focus:border-red-500 focus:ring-red-500/50' 
              : 'border-gray-600 focus:border-cyan-500 focus:ring-cyan-500/50'
          }`}
        />
        {urlError && (
          <p className="mt-1 text-xs text-red-400 flex items-center gap-1">
            <AlertCircle size={12} />
            {urlError}
          </p>
        )}
      </div>

      {/* SRT File Upload */}
      <div>
        <label className="text-sm font-medium text-gray-300 mb-2 block">
          {t('srtSubtitleFileLabel')}
        </label>
        <div className="flex gap-2">
          <input
            ref={fileInputRef}
            type="file"
            accept=".srt"
            onChange={handleFileSelected}
            disabled={isLoading}
            className="hidden"
          />
          <button
            onClick={() => fileInputRef.current?.click()}
            disabled={isLoading}
            className="flex-1 px-4 py-2 bg-gray-700 hover:bg-gray-600 text-white rounded-lg border border-gray-600 transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
          >
            <Upload size={18} />
            {selectedFile ? selectedFile.name : t('chooseSrtFile')}
          </button>
          {selectedFile && (
            <button
              onClick={() => {
                setSelectedFile(null);
                if (fileInputRef.current) {
                  fileInputRef.current.value = '';
                }
              }}
              disabled={isLoading}
              className="px-3 py-2 bg-gray-700 hover:bg-gray-600 text-gray-400 hover:text-white rounded-lg border border-gray-600 transition-colors disabled:opacity-50"
              title={t('clearSelectedFile')}
            >
              ✕
            </button>
          )}
        </div>
      </div>

      {/* Error Display */}
      {error && (
        <div className="p-3 bg-red-900/30 border border-red-700 rounded-lg text-red-300 text-sm flex items-start gap-2">
          <AlertCircle size={16} className="mt-0.5 flex-shrink-0" />
          {error}
        </div>
      )}

      {/* Import Button */}
      <button
        onClick={handleImport}
        disabled={isLoading || !selectedFile || !youtubeUrl.trim() || !!urlError}
        className="w-full px-6 py-3 bg-cyan-600 hover:bg-cyan-700 text-white font-semibold rounded-lg transition-colors disabled:bg-gray-600 disabled:cursor-not-allowed flex items-center justify-center gap-2"
      >
        {isLoading ? (
          <>
            <svg className="animate-spin h-5 w-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
              <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
              <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
            </svg>
            {t('importing')}
          </>
        ) : (
          <>
            <Play size={18} />
            {t('importAndViewTranscript')}
          </>
        )}
      </button>

      <p className="text-xs text-gray-500">
        The SRT file will be parsed locally and used for transcript analysis
      </p>
    </div>
  );
};
