import React, { useState, useRef, useEffect } from 'react';
import { useTranscriptAnalysis } from '../hooks/useTranscriptAnalysis';
import { useSearchParams } from '../hooks/useSearchParams';
import { downloadTranscriptJson, downloadTranscriptText, TranscriptData } from '../utils/transcriptStorage';
import { downloadSpeakerAnalysisJson, parseSpeakerAnalysisFromJson } from '../utils/speakerStorage';
import { downloadAnalysisJson, parseAnalysisFromJson, FullAnalysisData } from '../utils/analysisStorage';
import { createSession, updateSessionStep } from '../utils/api';
import { TranscriptSegment, formatTimestamp, parseTimestamp, constructFormattedTranscript } from '../utils/transcriptHelpers';
import TranscriptViewHeader from './TranscriptViewer/TranscriptViewHeader';
import TranscriptSearchBar from './TranscriptViewer/TranscriptSearchBar';
import TranscriptSegmentList from './TranscriptViewer/TranscriptSegmentList';
import TopicAnalysisView from './TranscriptViewer/TopicAnalysisView';
import SpeakerAnalysisView from './TranscriptViewer/SpeakerAnalysisView';
import DialogAnalysisView from './TranscriptViewer/DialogAnalysisView';
import ViewModeTabs from './TranscriptViewer/ViewModeTabs';
import TranscriptFooter from './TranscriptViewer/TranscriptFooter';

interface TranscriptViewerProps {
  isOpen: boolean;
  onClose: () => void;
  segments: TranscriptSegment[];
  videoId: string;
  languageCode: string;
  isAutoGenerated: boolean;
  sessionId?: string;
  initialSessionData?: {
    topicAnalysis?: any[];
    speakerAnalysis?: any[];
    dialogAnalysis?: any[];
  };
  onSessionCreated?: (sessionId: string) => void;
}

export const TranscriptViewer: React.FC<TranscriptViewerProps> = ({
  isOpen,
  onClose,
  segments,
  videoId,
  languageCode,
  isAutoGenerated,
  sessionId,
  initialSessionData,
  onSessionCreated,
}) => {
  const [viewMode, setViewMode] = useState<'transcript' | 'topics' | 'speakers' | 'dialog'>(() => {
    if (initialSessionData?.dialogAnalysis && initialSessionData.dialogAnalysis.length > 0) return 'dialog';
    if (initialSessionData?.speakerAnalysis && initialSessionData.speakerAnalysis.length > 0) return 'speakers';
    if (initialSessionData?.topicAnalysis && initialSessionData.topicAnalysis.length > 0) return 'topics';
    return 'transcript';
  });
  const [searchTerm, setSearchTerm] = useState<string>('');
  const [filteredSegments, setFilteredSegments] = useState<TranscriptSegment[]>(segments);
  const [expandedBlocks, setExpandedBlocks] = useState<Set<string>>(new Set());
  const [highlightedDialogLineId, setHighlightedDialogLineId] = useState<string | null>(null);
  const [currentSessionId, setCurrentSessionId] = useState<string | undefined>(sessionId);
  const [isCreatingSession, setIsCreatingSession] = useState(false);
  const segmentRefs = useRef<(HTMLDivElement | null)[]>([]);
  const dialogLineRefs = useRef<Map<string, HTMLDivElement>>(new Map());
  const fileInputRef = useRef<HTMLInputElement>(null);
  const fullAnalysisInputRef = useRef<HTMLInputElement>(null);
  
  // Get API key info from search params
  const { selectedAI } = useSearchParams();
  
  // Topic analysis hook
  const topicAnalysis = useTranscriptAnalysis(initialSessionData);

  const formattedText = constructFormattedTranscript(segments);

  /**
   * Ensure a session exists and transcript is saved before analysis
   * Auto-creates session if needed
   */
  const ensureSession = async (): Promise<string | undefined> => {
    if (currentSessionId) {
      return currentSessionId;
    }

    if (isCreatingSession) {
      // Wait for session creation to complete
      return new Promise(resolve => {
        const checkInterval = setInterval(() => {
          if (currentSessionId) {
            clearInterval(checkInterval);
            resolve(currentSessionId);
          }
        }, 100);
        // Timeout after 5 seconds
        setTimeout(() => {
          clearInterval(checkInterval);
          resolve(undefined);
        }, 5000);
      });
    }

    setIsCreatingSession(true);
    try {
      const response = await createSession(`https://www.youtube.com/watch?v=${videoId}`, 'youtube');
      const newSessionId = response.data._id;
      
      // Save the transcript to the session
      await updateSessionStep(newSessionId, 'transcript', {
        videoId,
        languageCode,
        isAutoGenerated,
        segments
      }, 'extracting_transcript');
      
      setCurrentSessionId(newSessionId);
      if (onSessionCreated) {
        onSessionCreated(newSessionId);
      }
      return newSessionId;
    } catch (error) {
      console.error('Failed to auto-create session:', error);
      return undefined;
    } finally {
      setIsCreatingSession(false);
    }
  };

  // Filter segments based on search term
  useEffect(() => {
    if (!searchTerm.trim()) {
      setFilteredSegments(segments);
      return;
    }

    const filtered = segments.filter(segment =>
      segment.text.toLowerCase().includes(searchTerm.toLowerCase())
    );
    setFilteredSegments(filtered);
  }, [searchTerm, segments]);

  const handleCopyText = () => {
    navigator.clipboard.writeText(formattedText);
  };

  const handleDownloadTranscript = () => {
    downloadTranscriptText(segments, videoId);
  };

  const handleDownloadJSON = () => {
    const transcriptData: TranscriptData = {
      videoId,
      languageCode,
      isAutoGenerated,
      segments,
    };
    downloadTranscriptJson(transcriptData, videoId);
  };

  const handleSegmentClick = (start: number) => {
    const url = `https://www.youtube.com/watch?v=${videoId}&t=${Math.floor(start)}s`;
    window.open(url, '_blank');
  };

  const handleAnalyzeTopics = async () => {
    // Get API keys from localStorage
    const apiKeys: Record<string, string> = {};
    try {
      const stored = localStorage.getItem('apiKeys');
      if (stored) {
        const parsed = JSON.parse(stored);
        Object.assign(apiKeys, parsed);
      }
    } catch (e) {
      console.error('Failed to load API keys from localStorage', e);
    }

    // Ensure a session exists before analyzing
    const sId = await ensureSession();

    await topicAnalysis.analyzeTranscript(
      segments,
      languageCode,
      selectedAI || 'gemini',
      apiKeys,
      sId
    );
    setViewMode('topics');
  };

  const handleAnalyzeSpeakers = async () => {
    // Get API keys from localStorage
    const apiKeys: Record<string, string> = {};
    try {
      const stored = localStorage.getItem('apiKeys');
      if (stored) {
        const parsed = JSON.parse(stored);
        Object.assign(apiKeys, parsed);
      }
    } catch (e) {
      console.error('Failed to load API keys from localStorage', e);
    }

    // Ensure a session exists before analyzing
    const sId = await ensureSession();

    await topicAnalysis.analyzeSpeakers(
      languageCode,
      selectedAI || 'gemini',
      apiKeys,
      sId
    );
    setViewMode('speakers');
  };

  const handleAnalyzeDialog = async () => {
    // Get API keys from localStorage
    const apiKeys: Record<string, string> = {};
    try {
      const stored = localStorage.getItem('apiKeys');
      if (stored) {
        const parsed = JSON.parse(stored);
        Object.assign(apiKeys, parsed);
      }
    } catch (e) {
      console.error('Failed to load API keys from localStorage', e);
    }

    // Ensure a session exists before analyzing
    const sId = await ensureSession();

    await topicAnalysis.analyzeDialog(
      languageCode,
      'gemini-2.0-flash-exp', // Fast model
      'gemini-2.5-flash',       // Better model
      apiKeys,
      sId
    );
    setViewMode('dialog');
  };

  const toggleBlockExpand = (blockId: string) => {
    const newExpanded = new Set(expandedBlocks);
    if (newExpanded.has(blockId)) {
      newExpanded.delete(blockId);
    } else {
      newExpanded.add(blockId);
    }
    setExpandedBlocks(newExpanded);
  };

  /**
   * Handle clicking on a summary item to highlight and scroll to matching dialog
   */
  const handleSummaryItemClick = (groupId: string, timestamp: string, groupDialogLines: any[]) => {
    const targetSeconds = parseTimestamp(timestamp);
    if (targetSeconds === null) return;

    // Find the closest dialog line by timestamp
    let closestLine = groupDialogLines[0];
    let closestDiff = Math.abs(closestLine.timestamp - targetSeconds);

    for (const line of groupDialogLines) {
      const diff = Math.abs(line.timestamp - targetSeconds);
      if (diff < closestDiff) {
        closestDiff = diff;
        closestLine = line;
      }
    }

    // Create unique ID for this dialog line
    const lineId = `${groupId}-${groupDialogLines.indexOf(closestLine)}-${closestLine.timestamp}`;
    setHighlightedDialogLineId(lineId);

    // Scroll to the dialog line
    const element = dialogLineRefs.current.get(lineId);
    if (element) {
      element.scrollIntoView({
        behavior: 'smooth',
        block: 'nearest',
      });
    }

    // Clear highlight after 3 seconds
    setTimeout(() => {
      setHighlightedDialogLineId(null);
    }, 3000);
  };

  const handleExportSpeakers = () => {
    if (topicAnalysis.speakerResults.length > 0) {
      downloadSpeakerAnalysisJson(topicAnalysis.speakerResults, videoId);
    }
  };

  const handleImportSpeakersClick = () => {
    fileInputRef.current?.click();
  };

  const handleExportAnalysis = () => {
    const data: FullAnalysisData = {
      version: 1,
      timestamp: new Date().toISOString(),
      videoId,
      results: topicAnalysis.results,
      speakerResults: topicAnalysis.speakerResults,
      dialogResults: topicAnalysis.dialogResults,
    };
    downloadAnalysisJson(data, `analysis_${videoId}`);
  };

  const handleImportAnalysisClick = () => {
    fullAnalysisInputRef.current?.click();
  };

  const handleFullAnalysisFileChange = async (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;

    try {
      const data = await parseAnalysisFromJson(file);
      topicAnalysis.setFullAnalysisState(
        data.results || [],
        data.speakerResults || [],
        data.dialogResults || []
      );
      
      // Switch to the most advanced view available
      if (data.dialogResults && data.dialogResults.length > 0) {
        setViewMode('dialog');
      } else if (data.speakerResults && data.speakerResults.length > 0) {
        setViewMode('speakers');
      } else if (data.results && data.results.length > 0) {
        setViewMode('topics');
      }
      
    } catch (error) {
      console.error('Failed to import analysis:', error);
      alert('Failed to import analysis file. Please check the file format.');
    }
    
    // Reset input
    event.target.value = '';
  };

  const handleFileChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (e) => {
      try {
        const content = e.target?.result as string;
        const results = parseSpeakerAnalysisFromJson(content);
        topicAnalysis.setSpeakerResults(results);
        setViewMode('speakers');
      } catch (error) {
        console.error('Failed to import speaker analysis:', error);
        alert('Failed to import speaker analysis file. Please check the file format.');
      }
    };
    reader.readAsText(file);
    // Reset input
    event.target.value = '';
  };

  const handleSaveSession = async () => {
    if (currentSessionId) return;
    
    try {
      const response = await createSession(`https://www.youtube.com/watch?v=${videoId}`, 'youtube');
      const newSessionId = response.data._id;
      
      try {
        // Save the transcript to the session
        await updateSessionStep(newSessionId, 'transcript', {
          videoId,
          languageCode,
          isAutoGenerated,
          segments
        }, 'extracting_transcript');
        
        // Save topic analysis if available
        if (topicAnalysis.results.length > 0) {
          await updateSessionStep(newSessionId, 'topicAnalysis', topicAnalysis.results, 'analyzing_topics');
        }
        
        // Save speaker analysis if available
        if (topicAnalysis.speakerResults.length > 0) {
          await updateSessionStep(newSessionId, 'speakerAnalysis', topicAnalysis.speakerResults, 'identifying_speakers');
        }
        
        // Save dialog analysis if available (mark as completed)
        if (topicAnalysis.dialogResults.length > 0) {
          await updateSessionStep(newSessionId, 'dialogAnalysis', topicAnalysis.dialogResults, 'completed');
        } else if (topicAnalysis.speakerResults.length > 0) {
          // If only speaker analysis is available, mark as identifying_speakers
          // Do nothing as we already saved it above
        } else if (topicAnalysis.results.length > 0) {
          // If only topic analysis is available, mark as analyzing_topics
          // Do nothing as we already saved it above
        }
        
        setCurrentSessionId(newSessionId);
        if (onSessionCreated) {
          onSessionCreated(newSessionId);
        }
      } catch (updateError) {
        console.error('Failed to save session data:', updateError);
        alert('Failed to save all data to database. Session created but some data may not be saved.');
      }
    } catch (error) {
      console.error('Failed to create session:', error);
      alert('Failed to save session to database.');
    }
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
      <input
        type="file"
        ref={fileInputRef}
        onChange={handleFileChange}
        accept=".json"
        className="hidden"
      />
      <input
        type="file"
        ref={fullAnalysisInputRef}
        onChange={handleFullAnalysisFileChange}
        accept=".json"
        className="hidden"
      />
      <div className="bg-gray-900 rounded-xl shadow-2xl flex flex-col w-full max-w-4xl h-[90vh] border border-gray-700">
        <TranscriptViewHeader
          videoId={videoId}
          languageCode={languageCode}
          isAutoGenerated={isAutoGenerated}
          currentSessionId={currentSessionId}
          isCreatingSession={isCreatingSession}
          onClose={onClose}
          onSaveSession={handleSaveSession}
        />

        <ViewModeTabs
          viewMode={viewMode}
          topicResultsCount={topicAnalysis.results.length}
          speakerResultsCount={topicAnalysis.speakerResults.length}
          dialogResultsCount={topicAnalysis.dialogResults.length}
          isAnalyzing={topicAnalysis.isAnalyzing}
          onViewModeChange={setViewMode}
          onAnalyzeTopics={handleAnalyzeTopics}
        />

        {/* Transcript View */}
        {viewMode === 'transcript' && (
          <>
            <TranscriptSearchBar
              searchTerm={searchTerm}
              onSearchChange={setSearchTerm}
              onCopyText={handleCopyText}
              onDownloadTranscript={handleDownloadTranscript}
              onDownloadJSON={handleDownloadJSON}
              onImportSpeakers={handleImportSpeakersClick}
              onExportAnalysis={handleExportAnalysis}
              onImportAnalysis={handleImportAnalysisClick}
              onAnalyzeTopics={handleAnalyzeTopics}
              isAnalyzing={topicAnalysis.isAnalyzing}
            />

            <TranscriptSegmentList
              segments={segments}
              searchTerm={searchTerm}
              onSegmentClick={handleSegmentClick}
              segmentRefs={segmentRefs}
            />

            <TranscriptFooter
              filteredSegmentsCount={filteredSegments.length}
              totalSegmentsCount={segments.length}
              searchTerm={searchTerm}
            />
          </>
        )}

        {/* Topic Analysis View */}
        {viewMode === 'topics' && (
          <TopicAnalysisView
            isAnalyzing={topicAnalysis.isAnalyzing}
            analysisProgress={topicAnalysis.analysisProgress}
            results={topicAnalysis.results}
            error={topicAnalysis.error}
            selectedBlockIds={topicAnalysis.selectedBlockIds}
            isSpeakerAnalyzing={topicAnalysis.isSpeakerAnalyzing}
            onToggleBlockExpand={toggleBlockExpand}
            onToggleBlockSelection={topicAnalysis.toggleBlockSelection}
            onSelectAllBlocks={topicAnalysis.selectAllBlocks}
            onClearSelections={topicAnalysis.clearSelections}
            onSegmentClick={handleSegmentClick}
            onAnalyzeSpeakers={handleAnalyzeSpeakers}
            expandedBlocks={expandedBlocks}
          />
        )}

        {/* Speaker Analysis View */}
        {viewMode === 'speakers' && (
          <SpeakerAnalysisView
            isSpeakerAnalyzing={topicAnalysis.isSpeakerAnalyzing}
            speakerResults={topicAnalysis.speakerResults}
            error={topicAnalysis.error}
            onAnalyzeDialog={handleAnalyzeDialog}
            onImportSpeakers={handleImportSpeakersClick}
            onExportSpeakers={handleExportSpeakers}
            onClearAnalysis={topicAnalysis.clearAnalysis}
          />
        )}

        {/* Dialog Analysis View */}
        {viewMode === 'dialog' && (
          <DialogAnalysisView
            isDialogAnalyzing={topicAnalysis.isDialogAnalyzing}
            dialogResults={topicAnalysis.dialogResults}
            speakerResults={topicAnalysis.speakerResults}
            error={topicAnalysis.error}
            highlightedDialogLineId={highlightedDialogLineId}
            dialogLineRefs={dialogLineRefs}
            onSummaryItemClick={handleSummaryItemClick}
            onClearAnalysis={topicAnalysis.clearAnalysis}
            onAnalyzeDialog={handleAnalyzeDialog}
          />
        )}
      </div>
    </div>
  );
};

export default TranscriptViewer;
