import React, { useState, useRef } from 'react';
import { Upload, AlertCircle } from 'lucide-react';
import { parseTranscriptFromJson, parseTranscriptFromText, TranscriptData } from '../utils/transcriptStorage';

interface TranscriptImporterProps {
  onImport: (transcript: TranscriptData) => void;
  isLoading?: boolean;
}

export const TranscriptImporter: React.FC<TranscriptImporterProps> = ({
  onImport,
  isLoading = false,
}) => {
  const [error, setError] = useState<string | null>(null);
  const [importMode, setImportMode] = useState<'json' | 'text'>('json');
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [pastedContent, setPastedContent] = useState('');

  const handleFileSelected = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    setError(null);
    try {
      const content = await file.text();
      
      if (importMode === 'json') {
        const transcript = parseTranscriptFromJson(content);
        onImport(transcript);
      } else {
        const segments = parseTranscriptFromText(content);
        const transcript: TranscriptData = {
          videoId: 'imported',
          languageCode: 'en',
          isAutoGenerated: false,
          segments,
        };
        onImport(transcript);
      }
      
      // Reset
      setPastedContent('');
      if (fileInputRef.current) {
        fileInputRef.current.value = '';
      }
    } catch (err: any) {
      setError(err.message || 'Failed to import transcript');
    }
  };

  const handlePasteImport = () => {
    if (!pastedContent.trim()) {
      setError('Please paste transcript content');
      return;
    }

    setError(null);
    try {
      if (importMode === 'json') {
        const transcript = parseTranscriptFromJson(pastedContent);
        onImport(transcript);
      } else {
        const segments = parseTranscriptFromText(pastedContent);
        const transcript: TranscriptData = {
          videoId: 'imported',
          languageCode: 'en',
          isAutoGenerated: false,
          segments,
        };
        onImport(transcript);
      }
      setPastedContent('');
    } catch (err: any) {
      setError(err.message || 'Failed to import transcript');
    }
  };

  return (
    <div className="p-4 bg-gray-800/50 rounded-lg border border-gray-700 space-y-4">
      <h2 className="text-xl font-semibold text-cyan-400 mb-4 flex items-center gap-2">
        <Upload size={20} />
        Import Transcript Data
      </h2>

      <p className="text-sm text-gray-400">
        Skip YouTube fetching by importing previously downloaded transcript data
      </p>

      {/* Mode Selection */}
      <div className="flex gap-2">
        <button
          onClick={() => {
            setImportMode('json');
            setError(null);
          }}
          className={`flex-1 px-3 py-2 rounded-lg font-medium transition-colors ${
            importMode === 'json'
              ? 'bg-cyan-600 text-white'
              : 'bg-gray-700 text-gray-300 hover:bg-gray-600'
          }`}
        >
          JSON Format
        </button>
        <button
          onClick={() => {
            setImportMode('text');
            setError(null);
          }}
          className={`flex-1 px-3 py-2 rounded-lg font-medium transition-colors ${
            importMode === 'text'
              ? 'bg-cyan-600 text-white'
              : 'bg-gray-700 text-gray-300 hover:bg-gray-600'
          }`}
        >
          Text Format
        </button>
      </div>

      {/* File Upload */}
      <div>
        <label className="text-sm font-medium text-gray-300 mb-2 block">Upload File</label>
        <div className="relative">
          <input
            ref={fileInputRef}
            type="file"
            accept={importMode === 'json' ? '.json' : '.txt'}
            onChange={handleFileSelected}
            disabled={isLoading}
            className="hidden"
          />
          <button
            onClick={() => fileInputRef.current?.click()}
            disabled={isLoading}
            className="w-full px-4 py-2 bg-gray-700 hover:bg-gray-600 text-white rounded-lg border border-gray-600 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
          >
            Choose {importMode === 'json' ? 'JSON' : 'Text'} File
          </button>
        </div>
      </div>

      {/* Paste Mode */}
      <div>
        <label className="text-sm font-medium text-gray-300 mb-2 block">Or Paste Content</label>
        <textarea
          value={pastedContent}
          onChange={(e) => {
            setPastedContent(e.target.value);
            setError(null);
          }}
          placeholder={
            importMode === 'json'
              ? 'Paste JSON transcript export here...'
              : 'Paste text transcript here (format: [HH:MM:SS] text)...'
          }
          disabled={isLoading}
          rows={6}
          className="w-full bg-gray-700 text-white border border-gray-600 rounded-lg px-4 py-2 focus:outline-none focus:border-cyan-500 focus:ring-1 focus:ring-cyan-500/50 disabled:bg-gray-600 disabled:cursor-not-allowed font-mono text-xs"
        />
      </div>

      {/* Import Button */}
      <button
        onClick={handlePasteImport}
        disabled={isLoading || !pastedContent.trim()}
        className="w-full px-4 py-2 bg-cyan-600 hover:bg-cyan-700 text-white font-semibold rounded-lg transition-colors disabled:bg-gray-600 disabled:cursor-not-allowed"
      >
        {isLoading ? 'Importing...' : 'Import Transcript'}
      </button>

      {/* Error Message */}
      {error && (
        <div className="flex gap-2 p-3 bg-red-900/30 border border-red-700 rounded-lg text-red-300 text-sm">
          <AlertCircle size={18} className="flex-shrink-0 mt-0.5" />
          <span>{error}</span>
        </div>
      )}

      {/* Help Text */}
      <div className="text-xs text-gray-500 space-y-1">
        <p>
          <strong>JSON Format:</strong> Export from transcript viewer or use previously saved JSON files
        </p>
        <p>
          <strong>Text Format:</strong> One line per segment with timestamps [HH:MM:SS] or [MM:SS] format
        </p>
      </div>
    </div>
  );
};

export default TranscriptImporter;
