import React, { useState, useRef, useEffect } from 'react';
import { X, Copy, Download, Search as SearchIcon, Zap, ChevronDown, ChevronUp, Check, FileJson, Upload } from 'lucide-react';
import { useTranscriptAnalysis } from '../hooks/useTranscriptAnalysis';
import TopicTagCloud from './TopicTagCloud';
import { useSearchParams } from '../hooks/useSearchParams';
import Spinner from './Spinner';
import { downloadTranscriptJson, downloadTranscriptText, TranscriptData } from '../utils/transcriptStorage';
import { downloadSpeakerAnalysisJson, parseSpeakerAnalysisFromJson } from '../utils/speakerStorage';
import { downloadAnalysisJson, parseAnalysisFromJson, FullAnalysisData } from '../utils/analysisStorage';
import { createSession, updateSessionStep } from '../utils/api';

interface TranscriptSegment {
  start: number;
  duration: number;
  text: string;
}

interface TranscriptViewerProps {
  isOpen: boolean;
  onClose: () => void;
  segments: TranscriptSegment[];
  videoId: string;
  languageCode: string;
  isAutoGenerated: boolean;
  sessionId?: string;
  initialSessionData?: {
    topicAnalysis?: any[];
    speakerAnalysis?: any[];
    dialogAnalysis?: any[];
  };
  onSessionCreated?: (sessionId: string) => void;
}

/**
 * Formats seconds as HH:MM:SS timestamp
 */
function formatTimestamp(seconds: number): string {
  const hours = Math.floor(seconds / 3600);
  const minutes = Math.floor((seconds % 3600) / 60);
  const secs = Math.floor(seconds % 60);
  return `${hours.toString().padStart(2, '0')}:${minutes.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`;
}

/**
 * Constructs formatted transcript text with timestamps
 */
function constructFormattedTranscript(segments: TranscriptSegment[]): string {
  return segments
    .map(segment => `[${formatTimestamp(segment.start)}] ${segment.text}`)
    .join('\n');
}

export const TranscriptViewer: React.FC<TranscriptViewerProps> = ({
  isOpen,
  onClose,
  segments,
  videoId,
  languageCode,
  isAutoGenerated,
  sessionId,
  initialSessionData,
  onSessionCreated,
}) => {
  const [viewMode, setViewMode] = useState<'transcript' | 'topics' | 'speakers' | 'dialog'>(() => {
    if (initialSessionData?.dialogAnalysis && initialSessionData.dialogAnalysis.length > 0) return 'dialog';
    if (initialSessionData?.speakerAnalysis && initialSessionData.speakerAnalysis.length > 0) return 'speakers';
    if (initialSessionData?.topicAnalysis && initialSessionData.topicAnalysis.length > 0) return 'topics';
    return 'transcript';
  });
  const [searchTerm, setSearchTerm] = useState<string>('');
  const [filteredSegments, setFilteredSegments] = useState<TranscriptSegment[]>(segments);
  const [highlightedIndex, setHighlightedIndex] = useState<number | null>(null);
  const [expandedBlocks, setExpandedBlocks] = useState<Set<string>>(new Set());
  const scrollContainerRef = useRef<HTMLDivElement>(null);
  const segmentRefs = useRef<(HTMLDivElement | null)[]>([]);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const fullAnalysisInputRef = useRef<HTMLInputElement>(null);
  
  // Get API key info from search params
  const { selectedAI } = useSearchParams();
  
  // Topic analysis hook
  const topicAnalysis = useTranscriptAnalysis(initialSessionData);

  const formattedText = constructFormattedTranscript(segments);

  // Filter segments based on search term
  useEffect(() => {
    if (!searchTerm.trim()) {
      setFilteredSegments(segments);
      setHighlightedIndex(null);
      return;
    }

    const filtered = segments.filter(segment =>
      segment.text.toLowerCase().includes(searchTerm.toLowerCase())
    );
    setFilteredSegments(filtered);
    setHighlightedIndex(filtered.length > 0 ? 0 : null);
  }, [searchTerm, segments]);

  // Scroll to highlighted segment
  useEffect(() => {
    if (highlightedIndex !== null && segmentRefs.current[highlightedIndex]) {
      segmentRefs.current[highlightedIndex]?.scrollIntoView({
        behavior: 'smooth',
        block: 'center',
      });
    }
  }, [highlightedIndex]);

  const handleCopyText = () => {
    navigator.clipboard.writeText(formattedText);
  };

  const handleDownloadTranscript = () => {
    downloadTranscriptText(segments, videoId);
  };

  const handleDownloadJSON = () => {
    const transcriptData: TranscriptData = {
      videoId,
      languageCode,
      isAutoGenerated,
      segments,
    };
    downloadTranscriptJson(transcriptData, videoId);
  };

  const handleSegmentClick = (start: number) => {
    const url = `https://www.youtube.com/watch?v=${videoId}&t=${Math.floor(start)}s`;
    window.open(url, '_blank');
  };

  const handleAnalyzeTopics = async () => {
    // Get API keys from localStorage
    const apiKeys: Record<string, string> = {};
    try {
      const stored = localStorage.getItem('apiKeys');
      if (stored) {
        const parsed = JSON.parse(stored);
        Object.assign(apiKeys, parsed);
      }
    } catch (e) {
      console.error('Failed to load API keys from localStorage', e);
    }

    await topicAnalysis.analyzeTranscript(
      segments,
      languageCode,
      selectedAI || 'gemini',
      apiKeys,
      sessionId
    );
    setViewMode('topics');
  };

  const handleAnalyzeSpeakers = async () => {
    // Get API keys from localStorage
    const apiKeys: Record<string, string> = {};
    try {
      const stored = localStorage.getItem('apiKeys');
      if (stored) {
        const parsed = JSON.parse(stored);
        Object.assign(apiKeys, parsed);
      }
    } catch (e) {
      console.error('Failed to load API keys from localStorage', e);
    }

    await topicAnalysis.analyzeSpeakers(
      languageCode,
      selectedAI || 'gemini',
      apiKeys,
      sessionId
    );
    setViewMode('speakers');
  };

  const handleAnalyzeDialog = async () => {
    // Get API keys from localStorage
    const apiKeys: Record<string, string> = {};
    try {
      const stored = localStorage.getItem('apiKeys');
      if (stored) {
        const parsed = JSON.parse(stored);
        Object.assign(apiKeys, parsed);
      }
    } catch (e) {
      console.error('Failed to load API keys from localStorage', e);
    }

    await topicAnalysis.analyzeDialog(
      languageCode,
      'gemini-2.0-flash-exp', // Fast model
      'gemini-2.5-flash',       // Better model
      apiKeys,
      sessionId
    );
    setViewMode('dialog');
  };

  const toggleBlockExpand = (blockId: string) => {
    const newExpanded = new Set(expandedBlocks);
    if (newExpanded.has(blockId)) {
      newExpanded.delete(blockId);
    } else {
      newExpanded.add(blockId);
    }
    setExpandedBlocks(newExpanded);
  };

  const handleExportSpeakers = () => {
    if (topicAnalysis.speakerResults.length > 0) {
      downloadSpeakerAnalysisJson(topicAnalysis.speakerResults, videoId);
    }
  };

  const handleImportSpeakersClick = () => {
    fileInputRef.current?.click();
  };

  const handleExportAnalysis = () => {
    const data: FullAnalysisData = {
      version: 1,
      timestamp: new Date().toISOString(),
      videoId,
      results: topicAnalysis.results,
      speakerResults: topicAnalysis.speakerResults,
      dialogResults: topicAnalysis.dialogResults,
    };
    downloadAnalysisJson(data, `analysis_${videoId}`);
  };

  const handleImportAnalysisClick = () => {
    fullAnalysisInputRef.current?.click();
  };

  const handleFullAnalysisFileChange = async (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;

    try {
      const data = await parseAnalysisFromJson(file);
      topicAnalysis.setFullAnalysisState(
        data.results || [],
        data.speakerResults || [],
        data.dialogResults || []
      );
      
      // Switch to the most advanced view available
      if (data.dialogResults && data.dialogResults.length > 0) {
        setViewMode('dialog');
      } else if (data.speakerResults && data.speakerResults.length > 0) {
        setViewMode('speakers');
      } else if (data.results && data.results.length > 0) {
        setViewMode('topics');
      }
      
    } catch (error) {
      console.error('Failed to import analysis:', error);
      alert('Failed to import analysis file. Please check the file format.');
    }
    
    // Reset input
    event.target.value = '';
  };

  const handleFileChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (e) => {
      try {
        const content = e.target?.result as string;
        const results = parseSpeakerAnalysisFromJson(content);
        topicAnalysis.setSpeakerResults(results);
        setViewMode('speakers');
      } catch (error) {
        console.error('Failed to import speaker analysis:', error);
        alert('Failed to import speaker analysis file. Please check the file format.');
      }
    };
    reader.readAsText(file);
    // Reset input
    event.target.value = '';
  };

  const handleSaveSession = async () => {
    if (sessionId) return;
    
    try {
      const response = await createSession(`https://www.youtube.com/watch?v=${videoId}`, 'youtube');
      const newSessionId = response.data._id;
      
      // Save the transcript to the session
      await updateSessionStep(newSessionId, 'transcript', {
        videoId,
        languageCode,
        isAutoGenerated,
        segments
      }, 'extracting_transcript');
      
      if (onSessionCreated) {
        onSessionCreated(newSessionId);
      }
    } catch (error) {
      console.error('Failed to save session:', error);
      alert('Failed to save session to database.');
    }
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
      <input
        type="file"
        ref={fileInputRef}
        onChange={handleFileChange}
        accept=".json"
        className="hidden"
      />
      <input
        type="file"
        ref={fullAnalysisInputRef}
        onChange={handleFullAnalysisFileChange}
        accept=".json"
        className="hidden"
      />
      <div className="bg-gray-900 rounded-xl shadow-2xl flex flex-col w-full max-w-4xl h-[90vh] border border-gray-700">
        {/* Header */}
        <div className="flex justify-between items-center p-6 border-b border-gray-700 flex-shrink-0">
          <div className="flex-1">
            <h2 className="text-2xl font-bold text-white">YouTube Transcript</h2>
            <div className="mt-2 flex gap-4 text-sm text-gray-400">
              <span>
                Video ID: <span className="text-gray-300 font-mono">{videoId}</span>
              </span>
              <span>
                Language: <span className="text-gray-300">{languageCode}</span>
              </span>
              {isAutoGenerated && (
                <span className="text-amber-400 flex items-center gap-1">
                  ⚠️ Auto-generated captions
                </span>
              )}
              {sessionId ? (
                <span className="text-green-400 flex items-center gap-1 ml-4">
                  <Check size={14} /> Saved to DB
                </span>
              ) : (
                <button
                  onClick={handleSaveSession}
                  className="ml-4 px-3 py-1 bg-cyan-600/20 hover:bg-cyan-600/40 text-cyan-400 rounded text-xs border border-cyan-600/50 transition-colors"
                >
                  Save to DB
                </button>
              )}
            </div>
          </div>
          <button
            onClick={onClose}
            className="text-gray-400 hover:text-white transition-colors p-2 hover:bg-gray-800 rounded-lg"
            title="Close"
          >
            <X size={24} />
          </button>
        </div>

        {/* View Mode Tabs */}
        <div className="flex gap-2 p-4 border-b border-gray-700 flex-shrink-0 bg-gray-800/30">
          <button
            onClick={() => setViewMode('transcript')}
            className={`px-4 py-2 rounded-lg font-medium transition-colors ${
              viewMode === 'transcript'
                ? 'bg-cyan-600 text-white'
                : 'bg-gray-700 text-gray-300 hover:bg-gray-600'
            }`}
          >
            Transcript
          </button>
          <button
            onClick={() => {
              if (topicAnalysis.results.length === 0) {
                handleAnalyzeTopics();
              } else {
                setViewMode('topics');
              }
            }}
            disabled={topicAnalysis.isAnalyzing}
            className={`px-4 py-2 rounded-lg font-medium transition-colors flex items-center gap-2 ${
              viewMode === 'topics'
                ? 'bg-cyan-600 text-white'
                : 'bg-gray-700 text-gray-300 hover:bg-gray-600 disabled:opacity-50'
            }`}
          >
            <Zap size={16} />
            Topics {topicAnalysis.results.length > 0 && `(${topicAnalysis.results.length})`}
          </button>
          <button
            onClick={() => setViewMode('speakers')}
            className={`px-4 py-2 rounded-lg font-medium transition-colors flex items-center gap-2 ${
              viewMode === 'speakers'
                ? 'bg-cyan-600 text-white'
                : 'bg-gray-700 text-gray-300 hover:bg-gray-600'
            }`}
          >
            Speakers {topicAnalysis.speakerResults.length > 0 && `(${topicAnalysis.speakerResults.length})`}
          </button>
          <button
            onClick={() => setViewMode('dialog')}
            disabled={topicAnalysis.speakerResults.length === 0}
            className={`px-4 py-2 rounded-lg font-medium transition-colors flex items-center gap-2 ${
              viewMode === 'dialog'
                ? 'bg-cyan-600 text-white'
                : 'bg-gray-700 text-gray-300 hover:bg-gray-600 disabled:opacity-50'
            }`}
          >
            Dialog Analysis {topicAnalysis.dialogResults.length > 0 && `(${topicAnalysis.dialogResults.length})`}
          </button>
        </div>

        {/* Transcript View */}
        {viewMode === 'transcript' && (
          <>
            {/* Search and Actions Bar */}
            <div className="flex gap-3 p-4 border-b border-gray-700 flex-shrink-0">
              <div className="flex-1 relative">
                <SearchIcon size={18} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-500" />
                <input
                  type="text"
                  placeholder="Search in transcript..."
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  className="w-full bg-gray-800 text-white border border-gray-700 rounded-lg py-2 pl-10 pr-4 focus:outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-500/50"
                />
              </div>
              <button
                onClick={handleCopyText}
                className="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg flex items-center gap-2 transition-colors"
                title="Copy all text to clipboard"
              >
                <Copy size={18} />
                <span className="hidden sm:inline">Copy</span>
              </button>
              <button
                onClick={handleDownloadTranscript}
                className="bg-green-600 hover:bg-green-700 text-white px-4 py-2 rounded-lg flex items-center gap-2 transition-colors"
                title="Download transcript as text file"
              >
                <Download size={18} />
                <span className="hidden sm:inline">Download TXT</span>
              </button>
              <button
                onClick={handleDownloadJSON}
                className="bg-emerald-600 hover:bg-emerald-700 text-white px-4 py-2 rounded-lg flex items-center gap-2 transition-colors"
                title="Download transcript as JSON for re-import"
              >
                <FileJson size={18} />
                <span className="hidden sm:inline">Download JSON</span>
              </button>
              <button
                onClick={handleImportSpeakersClick}
                className="bg-indigo-600 hover:bg-indigo-700 text-white px-4 py-2 rounded-lg flex items-center gap-2 transition-colors"
                title="Import previously analyzed speakers data"
              >
                <Upload size={18} />
                <span className="hidden sm:inline">Import Speakers</span>
              </button>
              <button
                onClick={handleExportAnalysis}
                className="bg-teal-600 hover:bg-teal-700 text-white px-4 py-2 rounded-lg flex items-center gap-2 transition-colors"
                title="Export full analysis state"
              >
                <Download size={18} />
                <span className="hidden sm:inline">Export Analysis</span>
              </button>
              <button
                onClick={handleImportAnalysisClick}
                className="bg-orange-600 hover:bg-orange-700 text-white px-4 py-2 rounded-lg flex items-center gap-2 transition-colors"
                title="Import full analysis state"
              >
                <Upload size={18} />
                <span className="hidden sm:inline">Import Analysis</span>
              </button>
              <button
                onClick={handleAnalyzeTopics}
                disabled={topicAnalysis.isAnalyzing}
                className="bg-purple-600 hover:bg-purple-700 text-white px-4 py-2 rounded-lg flex items-center gap-2 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                title="Analyze topics in transcript"
              >
                {topicAnalysis.isAnalyzing ? (
                  <Spinner />
                ) : (
                  <Zap size={18} />
                )}
                <span className="hidden sm:inline">Analyze Topics</span>
              </button>
            </div>

            {/* Main Transcript Area */}
            <div
              ref={scrollContainerRef}
              className="flex-1 overflow-y-auto p-6 bg-gray-800/30"
            >
              {filteredSegments.length > 0 ? (
                <div className="space-y-3 font-mono text-sm">
                  {filteredSegments.map((segment, index) => {
                    const isHighlighted = searchTerm && segment.text.toLowerCase().includes(searchTerm.toLowerCase());
                    const displayIndex = segments.indexOf(segment);

                    return (
                      <div
                        key={displayIndex}
                        ref={(el) => {
                          if (el !== null) {
                            segmentRefs.current[index] = el;
                          }
                        }}
                        onClick={() => handleSegmentClick(segment.start)}
                        className={`p-3 rounded-lg border transition-all cursor-pointer group ${
                          isHighlighted
                            ? 'bg-blue-900/40 border-blue-500 text-blue-100'
                            : 'bg-gray-800/40 border-gray-700 text-gray-300 hover:bg-gray-800/60 hover:border-gray-600'
                        }`}
                      >
                        <div className="flex gap-3">
                          <span className="text-blue-400 font-bold flex-shrink-0 min-w-fit group-hover:text-blue-300">
                            [{formatTimestamp(segment.start)}]
                          </span>
                          <span className="flex-1 leading-relaxed break-words">{segment.text}</span>
                        </div>
                      </div>
                    );
                  })}
                </div>
              ) : (
                <div className="flex items-center justify-center h-full text-gray-500">
                  <p>
                    {searchTerm
                      ? `No results found for "${searchTerm}"`
                      : 'No transcript segments available'}
                  </p>
                </div>
              )}
            </div>

            {/* Footer Info */}
            <div className="border-t border-gray-700 px-6 py-3 bg-gray-800/50 text-xs text-gray-400 flex-shrink-0">
              <span>
                Showing {filteredSegments.length} of {segments.length} segments
                {searchTerm && ` (searched for "${searchTerm}")`}
              </span>
            </div>
          </>
        )}

        {/* Topic Analysis View */}
        {viewMode === 'topics' && (
          <>
            {topicAnalysis.isAnalyzing && (
              <div className="flex-1 flex items-center justify-center bg-gray-800/30">
                <div className="text-center">
                  <Spinner />
                  <p className="mt-4 text-gray-300">
                    Analyzing topics... {Math.round(topicAnalysis.analysisProgress)}%
                  </p>
                </div>
              </div>
            )}

            {!topicAnalysis.isAnalyzing && topicAnalysis.results.length > 0 && (
              <div className="flex-1 overflow-y-auto p-6 bg-gray-800/30 space-y-4">
                <div className="flex justify-between items-center mb-4">
                  <p className="text-gray-300">
                    Found <strong>{topicAnalysis.results.length}</strong> transcript blocks with topics
                  </p>
                  <div className="flex gap-2">
                    <button
                      onClick={topicAnalysis.selectAllBlocks}
                      className="text-xs px-3 py-1 bg-blue-600/30 text-blue-300 rounded hover:bg-blue-600/50"
                    >
                      Select All
                    </button>
                    <button
                      onClick={topicAnalysis.clearSelections}
                      className="text-xs px-3 py-1 bg-gray-700 text-gray-300 rounded hover:bg-gray-600"
                    >
                      Clear
                    </button>
                  </div>
                </div>

                {topicAnalysis.results.map(block => (
                  <div
                    key={block.blockId}
                    className="bg-gray-800/60 border border-gray-700 rounded-lg overflow-hidden hover:border-gray-600 transition-colors"
                  >
                    {/* Block Header */}
                    <div
                      onClick={() => toggleBlockExpand(block.blockId)}
                      className="p-4 cursor-pointer hover:bg-gray-800/80 transition-colors flex items-center justify-between"
                    >
                      <div className="flex-1">
                        <div className="flex items-center gap-3 mb-2">
                          <button
                            onClick={(e) => {
                              e.stopPropagation();
                              topicAnalysis.toggleBlockSelection(block.blockId);
                            }}
                            className={`w-5 h-5 rounded border flex items-center justify-center transition-colors ${
                              block.isSelected
                                ? 'bg-green-600 border-green-500'
                                : 'border-gray-500 hover:border-gray-400'
                            }`}
                          >
                            {block.isSelected && <Check size={16} className="text-white" />}
                          </button>
                          <span className="font-mono text-sm text-blue-400">
                            {formatTimestamp(block.startTime)} - {formatTimestamp(block.endTime)}
                          </span>
                          <button
                            onClick={(e) => {
                              e.stopPropagation();
                              handleSegmentClick(block.startTime);
                            }}
                            className="text-xs px-2 py-1 bg-blue-600/30 text-blue-300 rounded hover:bg-blue-600/50"
                          >
                            Jump to Video
                          </button>
                        </div>
                        <p className="text-sm text-gray-300 line-clamp-2">{block.summary}</p>
                      </div>
                      {expandedBlocks.has(block.blockId) ? (
                        <ChevronUp size={20} className="text-gray-400 ml-2" />
                      ) : (
                        <ChevronDown size={20} className="text-gray-400 ml-2" />
                      )}
                    </div>

                    {/* Block Content */}
                    {expandedBlocks.has(block.blockId) && (
                      <div className="p-4 border-t border-gray-700 bg-gray-900/50 space-y-4">
                        <TopicTagCloud tags={block.tags} mainTopics={block.mainTopics} />
                        <div className="mt-3 pt-3 border-t border-gray-700">
                          <p className="text-xs text-gray-400 mb-2 font-semibold">Block Text:</p>
                          <p className="text-xs text-gray-400 line-clamp-4">{block.text}</p>
                        </div>
                      </div>
                    )}
                  </div>
                ))}

                {topicAnalysis.selectedBlockIds.size > 0 && (
                  <div className="sticky bottom-0 p-4 bg-gray-900 border-t border-gray-700 rounded-lg mt-4">
                    <p className="text-sm text-gray-300 mb-2">
                      <strong>{topicAnalysis.selectedBlockIds.size}</strong> blocks selected for detailed analysis
                    </p>
                    <button
                      onClick={handleAnalyzeSpeakers}
                      disabled={topicAnalysis.isSpeakerAnalyzing}
                      className="w-full bg-purple-600 hover:bg-purple-700 text-white px-4 py-2 rounded-lg font-medium transition-colors disabled:opacity-50 flex items-center justify-center gap-2"
                    >
                      {topicAnalysis.isSpeakerAnalyzing ? <Spinner /> : <Zap size={18} />}
                      Analyze Selected Blocks (Identify Speakers)
                    </button>
                  </div>
                )}
              </div>
            )}

            {!topicAnalysis.isAnalyzing && topicAnalysis.error && (
              <div className="flex-1 flex items-center justify-center bg-gray-800/30">
                <div className="text-center text-red-400">
                  <p>Error analyzing topics:</p>
                  <p className="text-sm text-red-300 mt-2">{topicAnalysis.error}</p>
                </div>
              </div>
            )}
          </>
        )}

        {/* Speaker Analysis View */}
        {viewMode === 'speakers' && (
          <>
            {topicAnalysis.isSpeakerAnalyzing && (
              <div className="flex-1 flex items-center justify-center bg-gray-800/30">
                <div className="text-center">
                  <Spinner />
                  <p className="mt-4 text-gray-300">
                    Identifying speakers...
                  </p>
                </div>
              </div>
            )}

            {!topicAnalysis.isSpeakerAnalyzing && topicAnalysis.speakerResults.length === 0 && (
              <div className="flex-1 flex items-center justify-center bg-gray-800/30">
                <div className="text-center text-gray-400">
                  <p className="mb-4">No speaker analysis data available.</p>
                  <button
                    onClick={handleImportSpeakersClick}
                    className="bg-gray-700 hover:bg-gray-600 text-white px-4 py-2 rounded-lg flex items-center gap-2 mx-auto transition-colors"
                  >
                    <Upload size={18} />
                    Import Analysis JSON
                  </button>
                </div>
              </div>
            )}

            {!topicAnalysis.isSpeakerAnalyzing && topicAnalysis.speakerResults.length > 0 && (
              <div className="flex-1 overflow-y-auto p-6 bg-gray-800/30 space-y-6">
                <div className="flex justify-between items-center mb-4">
                  <p className="text-gray-300">
                    Analyzed <strong>{topicAnalysis.speakerResults.length}</strong> blocks
                  </p>
                  <div className="flex gap-2">
                    <button
                      onClick={handleAnalyzeDialog}
                      className="text-xs px-3 py-1 bg-purple-600 text-white rounded hover:bg-purple-700 flex items-center gap-1"
                    >
                      <Zap size={12} />
                      Analyze Dialog Topics
                    </button>
                    <button
                      onClick={handleImportSpeakersClick}
                      className="text-xs px-3 py-1 bg-blue-600/30 text-blue-300 rounded hover:bg-blue-600/50 flex items-center gap-1"
                    >
                      <Upload size={12} />
                      Import
                    </button>
                    <button
                      onClick={handleExportSpeakers}
                      className="text-xs px-3 py-1 bg-emerald-600/30 text-emerald-300 rounded hover:bg-emerald-600/50 flex items-center gap-1"
                    >
                      <Download size={12} />
                      Export JSON
                    </button>
                    <button
                      onClick={() => topicAnalysis.clearAnalysis()}
                      className="text-xs px-3 py-1 bg-gray-700 text-gray-300 rounded hover:bg-gray-600"
                    >
                      Clear Analysis
                    </button>
                  </div>
                </div>

                {topicAnalysis.speakerResults.map(block => (
                  <div
                    key={block.blockId}
                    className="bg-gray-800/60 border border-gray-700 rounded-lg overflow-hidden"
                  >
                    <div className="p-3 bg-gray-900/50 border-b border-gray-700 flex justify-between items-center">
                      <span className="font-mono text-sm text-blue-400">
                        {formatTimestamp(block.startTime)} - {formatTimestamp(block.endTime)}
                      </span>
                      <div className="flex gap-2">
                        {block.identifiedSpeakers.map(speaker => (
                          <span key={speaker} className="text-xs px-2 py-1 bg-gray-700 rounded-full text-gray-300">
                            {speaker}
                          </span>
                        ))}
                      </div>
                    </div>
                    
                    <div className="p-4 space-y-4">
                      {block.dialogue.map((line, idx) => (
                        <div key={idx} className="flex gap-4">
                          <div className="w-32 flex-shrink-0 text-right">
                            <span className="text-sm font-bold text-purple-400 block truncate" title={line.speaker}>
                              {line.speaker}
                            </span>
                          </div>
                          <div className="flex-1">
                            <p className="text-gray-300 leading-relaxed">{line.text}</p>
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                ))}
              </div>
            )}
            
            {!topicAnalysis.isSpeakerAnalyzing && topicAnalysis.error && (
               <div className="flex-1 flex items-center justify-center bg-gray-800/30">
                <div className="text-center text-red-400">
                  <p>Error analyzing speakers:</p>
                  <p className="text-sm text-red-300 mt-2">{topicAnalysis.error}</p>
                </div>
              </div>
            )}
          </>
        )}

        {/* Dialog Analysis View */}
        {viewMode === 'dialog' && (
          <>
            {topicAnalysis.isDialogAnalyzing && (
              <div className="flex-1 flex items-center justify-center bg-gray-800/30">
                <div className="text-center">
                  <Spinner />
                  <p className="mt-4 text-gray-300">
                    Analyzing dialog topics...
                  </p>
                  <p className="text-sm text-gray-400 mt-2">This may take a while.</p>
                </div>
              </div>
            )}

            {!topicAnalysis.isDialogAnalyzing && topicAnalysis.dialogResults.length === 0 && (
              <div className="flex-1 flex items-center justify-center bg-gray-800/30">
                <div className="text-center text-gray-400">
                  <p className="mb-4">No dialog analysis data available.</p>
                  <button
                    onClick={handleAnalyzeDialog}
                    disabled={topicAnalysis.speakerResults.length === 0}
                    className="bg-purple-600 hover:bg-purple-700 text-white px-4 py-2 rounded-lg flex items-center gap-2 mx-auto transition-colors disabled:opacity-50"
                  >
                    <Zap size={18} />
                    Start Dialog Analysis
                  </button>
                </div>
              </div>
            )}

            {!topicAnalysis.isDialogAnalyzing && topicAnalysis.dialogResults.length > 0 && (
              <div className="flex-1 overflow-y-auto p-6 bg-gray-800/30 space-y-6">
                <div className="flex justify-between items-center mb-4">
                  <p className="text-gray-300">
                    Identified <strong>{topicAnalysis.dialogResults.length}</strong> topic groups
                  </p>
                  <div className="flex gap-2">
                    <button
                      onClick={() => topicAnalysis.clearAnalysis()}
                      className="text-xs px-3 py-1 bg-gray-700 text-gray-300 rounded hover:bg-gray-600"
                    >
                      Clear Analysis
                    </button>
                  </div>
                </div>

                {topicAnalysis.dialogResults.map(group => (
                  <div
                    key={group.id}
                    className="bg-gray-800/60 border border-gray-700 rounded-lg overflow-hidden"
                  >
                    <div className="p-4 bg-gray-900/50 border-b border-gray-700">
                      <h3 className="text-lg font-bold text-white mb-2">{group.title}</h3>
                      {group.analysis && (
                        <div className="bg-gray-800/50 p-3 rounded border border-gray-700/50">
                          <ul className="list-disc list-inside space-y-1">
                            {group.analysis.summaryItems.map((item, idx) => (
                              <li key={idx} className="text-sm text-gray-300">
                                <span className="text-gray-400 font-mono text-xs mr-2">[{item.timestamp}]</span>
                                <span>{item.text}</span>
                              </li>
                            ))}
                          </ul>
                        </div>
                      )}
                    </div>
                    
                    <div className="p-4 space-y-2 max-h-96 overflow-y-auto">
                      {group.dialogLines.map((line, idx) => (
                        <div key={idx} className="flex gap-4 text-sm">
                          <div className="w-24 flex-shrink-0 text-right">
                            <span className="font-mono text-gray-500 text-xs block">
                              {formatTimestamp(line.timestamp)}
                            </span>
                            <span className="font-bold text-purple-400 block truncate" title={line.speaker}>
                              {line.speaker}
                            </span>
                          </div>
                          <div className="flex-1">
                            <p className="text-gray-300">{line.text}</p>
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                ))}
              </div>
            )}

            {!topicAnalysis.isDialogAnalyzing && topicAnalysis.error && (
               <div className="flex-1 flex items-center justify-center bg-gray-800/30">
                <div className="text-center text-red-400">
                  <p>Error analyzing dialog:</p>
                  <p className="text-sm text-red-300 mt-2">{topicAnalysis.error}</p>
                </div>
              </div>
            )}
          </>
        )}
      </div>
    </div>
  );
};

export default TranscriptViewer;
