import React from 'react';
import { useTranscriptViewer } from '../hooks/useTranscriptViewer';
import TranscriptViewHeader from './TranscriptViewer/TranscriptViewHeader';
import TranscriptSearchBar from './TranscriptViewer/TranscriptSearchBar';
import TranscriptSegmentList from './TranscriptViewer/TranscriptSegmentList';
import TopicAnalysisView from './TranscriptViewer/TopicAnalysisView';
import SpeakerAnalysisView from './TranscriptViewer/SpeakerAnalysisView';
import DialogAnalysisView from './TranscriptViewer/DialogAnalysisView';
import StepProgressBar from './TranscriptViewer/StepProgressBar';
import TranscriptFooter from './TranscriptViewer/TranscriptFooter';
import { TranscriptSegment } from '../utils/transcriptHelpers';
import { promoteSession, updateQuoteSource } from '../utils/api';

interface TranscriptViewerProps {
  segments: TranscriptSegment[];
  videoId: string;
  languageCode: string;
  isAutoGenerated: boolean;
  sessionId?: string;
  initialSessionData?: {
    topicAnalysis?: any[];
    speakerAnalysis?: any[];
    dialogAnalysis?: any[];
  };
  onSessionCreated?: (sessionId: string) => void;
  onPromoteSuccess?: () => void;
  editQuoteId?: string;
  initialSelectedStatements?: Map<string, number>;
  contentAnalysisId?: string;
  lockedGroupId?: number;
}

export const TranscriptViewer: React.FC<TranscriptViewerProps> = (props) => {
  const {
    segments,
    videoId,
    languageCode,
    isAutoGenerated,
    editQuoteId,
    contentAnalysisId,
    lockedGroupId,
  } = props;

  const {
    viewMode,
    setViewMode,
    searchTerm,
    setSearchTerm,
    filteredSegments,
    expandedBlocks,
    highlightedDialogLineId,
    currentSessionId,
    isCreatingSession,
    segmentRefs,
    dialogLineRefs,
    fileInputRef,
    fullAnalysisInputRef,
    topicAnalysis,
    handleCopyText,
    handleDownloadTranscript,
    handleDownloadJSON,
    handleSegmentClick,
    handleAnalyzeTopics,
    handleAnalyzeSpeakers,
    handleAnalyzeDialog,
    toggleBlockExpand,
    handleSummaryItemClick,
    handleExportSpeakers,
    handleImportSpeakersClick,
    handleExportAnalysis,
    handleImportAnalysisClick,
    handleFullAnalysisFileChange,
    handleFileChange,
    handleSaveSession,
    selectedStatements,
    isSelectionMode,
    setIsSelectionMode,
    handleToggleSelection,
    handleGroupChange,
    selectedLanguage,
    setSelectedLanguage,
    getStepStatuses,
    handleStartStep,
    handleRenameSpeaker,
    handleAddSpeaker,
    checkSimilarPersonsBeforeAdd,
    handleRemoveSpeaker,
    handleUpdateLineSpeaker,
  } = useTranscriptViewer(props);

  const handlePromote = async () => {
    console.log('[handlePromote] Called with:', {
      editQuoteId,
      contentAnalysisId,
      currentSessionId,
      selectedStatementsSize: selectedStatements.size,
      selectedStatements: Array.from(selectedStatements.entries())
    });

    if (!currentSessionId && !contentAnalysisId) {
      console.error('[handlePromote] Neither sessionId nor contentAnalysisId found');
      alert('Error: No session or content analysis ID found');
      return;
    }
    
    const groups = new Map<number, string[]>();
    selectedStatements.forEach((groupId, statementId) => {
      if (!groups.has(groupId)) {
        groups.set(groupId, []);
      }
      groups.get(groupId)!.push(statementId);
    });
    
    const quoteGroups = Array.from(groups.entries()).map(([groupId, statementIds]) => ({
      groupId,
      statementIds
    }));
    
    console.log('[handlePromote] Quote groups:', quoteGroups);

    try {
      if (editQuoteId && contentAnalysisId) {
        console.log('[handlePromote] Edit mode - updating quote source');
        if (quoteGroups.length !== 1) {
          alert('Please select statements for exactly one group when editing a quote.');
          return;
        }
        await updateQuoteSource(editQuoteId, contentAnalysisId, quoteGroups[0].statementIds);
        alert('Successfully updated quote source!');
      } else {
        console.log('[handlePromote] Promote mode - creating new quotes');
        if (!currentSessionId) return;
        await promoteSession(currentSessionId, quoteGroups, selectedLanguage);
        alert('Successfully promoted to quotes!');
      }

      if (props.onPromoteSuccess) {
        props.onPromoteSuccess();
      }
    } catch (error) {
      console.error('[handlePromote] Error:', error);
      alert('Failed to promote quotes: ' + (error instanceof Error ? error.message : String(error)));
    }
  };

  return (
    <div className="flex flex-col w-full h-full bg-gray-900 border border-gray-700 rounded-lg overflow-hidden">
      <input
        type="file"
        ref={fileInputRef}
        onChange={handleFileChange}
        accept=".json"
        className="hidden"
      />
      <input
        type="file"
        ref={fullAnalysisInputRef}
        onChange={handleFullAnalysisFileChange}
        accept=".json"
        className="hidden"
      />

      {/* Header with video info and save button */}
      <div className="flex justify-between items-center p-4 border-b border-gray-700 flex-shrink-0">
        <div className="flex-1">
          <h3 className="text-lg font-semibold text-white">YouTube Transcript</h3>
          <div className="mt-1 flex gap-4 text-xs text-gray-400">
            <span>Video ID: <span className="text-gray-300 font-mono">{videoId}</span></span>
            <span>Language: <span className="text-gray-300">{languageCode}</span></span>
            {isAutoGenerated && <span className="text-amber-400">⚠️ Auto-generated</span>}
            {currentSessionId && <span className="text-green-400">✓ Saved to DB</span>}
          </div>
        </div>
        <button
          onClick={handleSaveSession}
          disabled={isCreatingSession || !!currentSessionId}
          className="px-3 py-1.5 bg-cyan-600/20 hover:bg-cyan-600/40 text-cyan-400 rounded text-xs border border-cyan-600/50 transition-colors disabled:opacity-50"
        >
          {currentSessionId ? 'Saved' : 'Save to DB'}
        </button>
      </div>

      {/* Step Progress Bar */}
      <StepProgressBar
        steps={getStepStatuses()}
        currentStep={viewMode}
        onStepClick={setViewMode}
        onStartStep={handleStartStep}
      />

      {/* Content Area */}
      <div className="flex-1 overflow-hidden flex flex-col">
        {/* Transcript View */}
        {viewMode === 'transcript' && (
          <>
            <TranscriptSearchBar
              searchTerm={searchTerm}
              onSearchChange={setSearchTerm}
              onCopyText={handleCopyText}
              onDownloadTranscript={handleDownloadTranscript}
              onDownloadJSON={handleDownloadJSON}
              onImportSpeakers={handleImportSpeakersClick}
              onExportAnalysis={handleExportAnalysis}
              onImportAnalysis={handleImportAnalysisClick}
              hasAnalysisData={
                topicAnalysis.results.length > 0 || 
                topicAnalysis.speakerResults.length > 0 || 
                topicAnalysis.dialogResults.length > 0
              }
            />

            <TranscriptSegmentList
              segments={segments}
              searchTerm={searchTerm}
              onSegmentClick={handleSegmentClick}
              segmentRefs={segmentRefs}
            />

            <TranscriptFooter
              filteredSegmentsCount={filteredSegments.length}
              totalSegmentsCount={segments.length}
              searchTerm={searchTerm}
            />
          </>
        )}

        {/* Topic Analysis View */}
        {viewMode === 'topics' && (
          <TopicAnalysisView
            isAnalyzing={topicAnalysis.isAnalyzing}
            analysisProgress={topicAnalysis.analysisProgress}
            results={topicAnalysis.results}
            error={topicAnalysis.error}
            selectedBlockIds={topicAnalysis.selectedBlockIds}
            isSpeakerAnalyzing={topicAnalysis.isSpeakerAnalyzing}
            onToggleBlockExpand={toggleBlockExpand}
            onToggleBlockSelection={topicAnalysis.toggleBlockSelection}
            onSelectAllBlocks={topicAnalysis.selectAllBlocks}
            onClearSelections={topicAnalysis.clearSelections}
            onClearAnalysis={topicAnalysis.clearTopicAnalysis}
            onSegmentClick={handleSegmentClick}
            onAnalyzeSpeakers={handleAnalyzeSpeakers}
            expandedBlocks={expandedBlocks}
          />
        )}

        {/* Speaker Analysis View */}
        {viewMode === 'speakers' && (
          <SpeakerAnalysisView
            isSpeakerAnalyzing={topicAnalysis.isSpeakerAnalyzing}
            speakerResults={topicAnalysis.speakerResults}
            error={topicAnalysis.error}
            onAnalyzeDialog={handleAnalyzeDialog}
            onImportSpeakers={handleImportSpeakersClick}
            onExportSpeakers={handleExportSpeakers}
            onClearAnalysis={topicAnalysis.clearSpeakerAnalysis}
            selectedLanguage={selectedLanguage}
            onLanguageChange={setSelectedLanguage}
            onRenameSpeaker={handleRenameSpeaker}
            onAddSpeaker={handleAddSpeaker}
            onCheckSimilarPersons={checkSimilarPersonsBeforeAdd}
            onRemoveSpeaker={handleRemoveSpeaker}
            onUpdateLineSpeaker={handleUpdateLineSpeaker}
          />
        )}

        {/* Dialog Analysis View */}
        {viewMode === 'dialog' && (
          <DialogAnalysisView
            isDialogAnalyzing={topicAnalysis.isDialogAnalyzing}
            dialogResults={topicAnalysis.dialogResults}
            speakerResults={topicAnalysis.speakerResults}
            error={topicAnalysis.error}
            highlightedDialogLineId={highlightedDialogLineId}
            dialogLineRefs={dialogLineRefs}
            onSummaryItemClick={handleSummaryItemClick}
            onClearAnalysis={topicAnalysis.clearDialogAnalysis}
            onAnalyzeDialog={handleAnalyzeDialog}
            isSelectionMode={isSelectionMode}
            selectedStatements={selectedStatements}
            onToggleSelection={handleToggleSelection}
            onGroupChange={handleGroupChange}
            onPromote={handlePromote}
            onStartSelection={() => setIsSelectionMode(true)}
            onCancelSelection={() => {
              setIsSelectionMode(false);
            }}
            selectedLanguage={selectedLanguage}
            onLanguageChange={setSelectedLanguage}
            lockedGroupId={lockedGroupId}
            isEditing={!!editQuoteId}
          />
        )}
      </div>
    </div>
  );
};

export default TranscriptViewer;
