import React, { useState } from 'react';
import { Youtube, AlertCircle, Copy, ExternalLink, HelpCircle } from 'lucide-react';
import { useI18n } from '../i18n';
import { 
  parseYoutubeTranscriptText, 
  extractYouTubeVideoId, 
  isYoutubeTranscriptFormat,
  isValidYouTubeUrl 
} from '../utils/youtubeTranscriptParser';
import { TranscriptData } from '../utils/transcriptStorage';

interface YoutubeTranscriptCopyPasteProps {
  onImport: (transcript: TranscriptData) => void;
  isLoading?: boolean;
}

export const YoutubeTranscriptCopyPaste: React.FC<YoutubeTranscriptCopyPasteProps> = ({
  onImport,
  isLoading = false,
}) => {
  const [youtubeUrl, setYoutubeUrl] = useState('');
  const [pastedTranscript, setPastedTranscript] = useState('');
  const [error, setError] = useState<string | null>(null);
  const [urlError, setUrlError] = useState<string | null>(null);
  const [showInstructions, setShowInstructions] = useState(false);
  const { t } = useI18n();

  const handleUrlChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const url = e.target.value;
    setYoutubeUrl(url);
    setUrlError(null);
    
    if (url.trim() && !isValidYouTubeUrl(url)) {
      setUrlError(t('pleaseEnterValidYouTubeUrl'));
    }
  };

  const handleTranscriptChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    const content = e.target.value;
    setPastedTranscript(content);
    setError(null);
  };

  const handleImport = () => {
    setError(null);
    setUrlError(null);

    // Validate YouTube URL
    if (!youtubeUrl.trim()) {
      setUrlError(t('pleaseEnterYoutubeUrl'));
      return;
    }

    const videoId = extractYouTubeVideoId(youtubeUrl);
    if (!videoId) {
      setUrlError('Please enter a valid YouTube URL');
      return;
    }

    // Validate transcript content
    if (!pastedTranscript.trim()) {
      setError(t('pleasePasteTranscriptText'));
      return;
    }

    // Check if it looks like YouTube transcript format
    if (!isYoutubeTranscriptFormat(pastedTranscript)) {
      setError(t('invalidYoutubeTranscriptFormat'));
      return;
    }

    try {
      const segments = parseYoutubeTranscriptText(pastedTranscript);

      const transcript: TranscriptData = {
        videoId,
        languageCode: 'unknown',
        isAutoGenerated: false,
        segments,
      };

      onImport(transcript);

      // Reset form
      setYoutubeUrl('');
      setPastedTranscript('');
    } catch (err: any) {
      setError(err.message || 'Failed to parse transcript');
    }
  };

  const handleKeyPress = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && e.ctrlKey && !isLoading && pastedTranscript.trim() && youtubeUrl.trim()) {
      handleImport();
    }
  };

  return (
    <div className="p-4 bg-gray-800/50 rounded-lg border border-gray-700 space-y-4">
      <div className="flex items-center justify-between">
        <h2 className="text-xl font-semibold text-cyan-400 flex items-center gap-2">
          <Youtube size={20} />
          YouTube Transcript (Copy & Paste)
        </h2>
        <button
          onClick={() => setShowInstructions(!showInstructions)}
          className="text-gray-400 hover:text-cyan-400 transition-colors"
          title={t('showInstructions')}
        >
          <HelpCircle size={20} />
        </button>
      </div>

      <p className="text-sm text-gray-400">
        {t('copyTranscriptNote')}
      </p>

      {/* Instructions Panel */}
      {showInstructions && (
        <div className="p-4 bg-gray-900/50 rounded-lg border border-gray-600 space-y-3">
          <h3 className="font-medium text-cyan-300 flex items-center gap-2">
            <Copy size={16} />
            {t('howToGetTranscript')}
          </h3>
          <ol className="text-sm text-gray-300 space-y-2 list-decimal list-inside">
            <li>{t('yt_step_open')}</li>
            <li>{t('yt_step_click_three_dots')}</li>
            <li>{t('yt_step_select_show_transcript')}</li>
            <li>{t('yt_step_toggle_timestamps')}</li>
            <li>{t('yt_step_select_all')}</li>
            <li>{t('yt_step_copy')}</li>
            <li>{t('yt_step_paste')}</li>
          </ol>
          <div className="flex items-center gap-2 text-xs text-gray-500">
            <ExternalLink size={14} />
            <span>{t('yt_tip_videos_may_not_have_transcripts')}</span>
          </div>
        </div>
      )}

      {/* YouTube URL Input */}
      <div>
        <label className="text-sm font-medium text-gray-300 mb-2 block">
          YouTube Video URL <span className="text-red-400">*</span>
        </label>
        <input
          type="url"
          value={youtubeUrl}
          onChange={handleUrlChange}
          onKeyDown={handleKeyPress}
          placeholder="https://www.youtube.com/watch?v=..."
          disabled={isLoading}
          className={`w-full bg-gray-700 text-white border rounded-lg px-4 py-2 focus:outline-none focus:ring-1 disabled:bg-gray-600 disabled:cursor-not-allowed ${
            urlError
              ? 'border-red-500 focus:border-red-500 focus:ring-red-500/50'
              : 'border-gray-600 focus:border-cyan-500 focus:ring-cyan-500/50'
          }`}
        />
        {urlError && (
          <p className="mt-1 text-sm text-red-400">{urlError}</p>
        )}
      </div>

      {/* Transcript Paste Area */}
      <div>
        <label className="text-sm font-medium text-gray-300 mb-2 block">
          Paste Transcript <span className="text-red-400">*</span>
        </label>
        <textarea
          value={pastedTranscript}
          onChange={handleTranscriptChange}
          onKeyDown={handleKeyPress}
          placeholder={`0:00\nHello everyone\n0:05\nWelcome to this video\n...`}
          disabled={isLoading}
          rows={8}
          className={`w-full bg-gray-700 text-white border rounded-lg px-4 py-2 focus:outline-none focus:ring-1 disabled:bg-gray-600 disabled:cursor-not-allowed font-mono text-sm ${
            error
              ? 'border-red-500 focus:border-red-500 focus:ring-red-500/50'
              : 'border-gray-600 focus:border-cyan-500 focus:ring-cyan-500/50'
          }`}
        />
        {pastedTranscript && (
          <p className="mt-1 text-xs text-gray-500">
            {pastedTranscript.split('\n').filter(l => l.trim()).length} lines pasted
          </p>
        )}
      </div>

      {/* Import Button */}
      <button
        onClick={handleImport}
        disabled={isLoading || !pastedTranscript.trim() || !youtubeUrl.trim()}
        className="w-full px-4 py-3 bg-red-600 hover:bg-red-700 text-white font-semibold rounded-lg transition-colors disabled:bg-gray-600 disabled:cursor-not-allowed flex items-center justify-center gap-2"
      >
        <Youtube size={18} />
        {isLoading ? t('processing') : t('importYouTubeTranscript')}
      </button>
      {error && (
        <p className="mt-2 text-sm text-red-400 text-center">{error}</p>
      )}

      {/* Keyboard Shortcut Hint */}
      <p className="text-xs text-gray-500 text-center">
        Press <kbd className="px-1.5 py-0.5 bg-gray-700 rounded text-gray-300">Ctrl</kbd> +{' '}
        <kbd className="px-1.5 py-0.5 bg-gray-700 rounded text-gray-300">Enter</kbd> to import
      </p>
    </div>
  );
};

export default YoutubeTranscriptCopyPaste;
