/**
 * YouTube Transcript Extractor Bookmarklet
 * 
 * This module generates a self-contained bookmarklet that users can drag to their
 * browser toolbar. When clicked on a YouTube page, it extracts the transcript
 * and copies it to the clipboard in a format ready for import.
 */

/**
 * The actual bookmarklet code that runs on YouTube pages
 * This is minified and URI-encoded for the bookmarklet href
 * 
 * NOTE: Uses regex-based XML parsing to avoid Trusted Types restrictions on YouTube
 */
const BOOKMARKLET_SOURCE = `
(function() {
  // Check if we're on YouTube
  if (!location.hostname.includes('youtube.com')) {
    alert('Please run this bookmarklet on a YouTube video page');
    return;
  }

  // Get video ID from URL
  const urlParams = new URLSearchParams(location.search);
  const videoId = urlParams.get('v');
  
  if (!videoId) {
    alert('Could not find video ID. Make sure you are on a YouTube video page (youtube.com/watch?v=...)');
    return;
  }

  // Helper: Parse XML using regex (avoids Trusted Types restrictions)
  function parseTranscriptXml(xml) {
    const segments = [];
    const textRegex = /<text\\s+start="([^"]*)"\\s+dur="([^"]*)"[^>]*>([^<]*)<\\/text>/g;
    let match;
    while ((match = textRegex.exec(xml)) !== null) {
      const text = match[3]
        .replace(/&#39;/g, "'")
        .replace(/&quot;/g, '"')
        .replace(/&amp;/g, '&')
        .replace(/&lt;/g, '<')
        .replace(/&gt;/g, '>')
        .replace(/\\\\n/g, ' ')
        .trim();
      if (text) {
        segments.push({
          start: parseFloat(match[1]) || 0,
          duration: parseFloat(match[2]) || 0,
          text: text
        });
      }
    }
    return segments;
  }

  // Helper: Decode HTML entities
  function decodeHtml(html) {
    const txt = document.createElement('textarea');
    txt.innerHTML = html;
    return txt.value;
  }

  // Try to find transcript data in the page
  let transcriptData = null;

  // Method 1: Look for ytInitialPlayerResponse in page scripts
  try {
    const scripts = document.querySelectorAll('script');
    for (const script of scripts) {
      const text = script.textContent || '';
      if (text.includes('ytInitialPlayerResponse')) {
        const match = text.match(/ytInitialPlayerResponse\\s*=\\s*(\\{.+?\\});/);
        if (match) {
          const playerResponse = JSON.parse(match[1]);
          const captions = playerResponse?.captions?.playerCaptionsTracklistRenderer?.captionTracks;
          if (captions && captions.length > 0) {
            // Found captions, fetch the first one
            const captionUrl = captions[0].baseUrl;
            fetch(captionUrl)
              .then(r => r.text())
              .then(xml => {
                // Use regex parsing instead of DOMParser to avoid Trusted Types
                const segments = parseTranscriptXml(xml);
                
                if (segments.length === 0) {
                  throw new Error('No segments found in transcript');
                }
                
                const result = {
                  videoId: videoId,
                  title: document.title.replace(' - YouTube', ''),
                  languageCode: captions[0].languageCode || 'unknown',
                  isAutoGenerated: (captions[0].kind === 'asr'),
                  segments: segments,
                  extractedAt: new Date().toISOString(),
                  source: 'bookmarklet'
                };
                
                const json = JSON.stringify(result, null, 2);
                navigator.clipboard.writeText(json).then(() => {
                  alert('✅ Transcript copied to clipboard!\\n\\nSegments: ' + segments.length + '\\nLanguage: ' + result.languageCode + '\\n\\nPaste it in the DoubleCheck AI import box.');
                }).catch(err => {
                  // Fallback: show in prompt for manual copy
                  prompt('Could not copy automatically. Copy this JSON manually:', json);
                });
              })
              .catch(err => {
                alert('Failed to fetch transcript: ' + err.message);
              });
            return;
          }
        }
      }
    }
  } catch (e) {
    console.error('Error extracting from ytInitialPlayerResponse:', e);
  }

  // Method 2: Try to get from the transcript panel if it's open
  try {
    const transcriptSegments = document.querySelectorAll('ytd-transcript-segment-renderer');
    if (transcriptSegments.length > 0) {
      const segments = [];
      transcriptSegments.forEach(seg => {
        const timestamp = seg.querySelector('.segment-timestamp')?.textContent?.trim() || '0:00';
        const text = seg.querySelector('.segment-text')?.textContent?.trim() || '';
        
        // Parse timestamp (M:SS or H:MM:SS)
        const parts = timestamp.split(':').map(p => parseInt(p, 10));
        let start = 0;
        if (parts.length === 2) {
          start = parts[0] * 60 + parts[1];
        } else if (parts.length === 3) {
          start = parts[0] * 3600 + parts[1] * 60 + parts[2];
        }
        
        if (text) {
          segments.push({ start, duration: 0, text });
        }
      });
      
      // Calculate durations
      for (let i = 0; i < segments.length; i++) {
        if (i < segments.length - 1) {
          segments[i].duration = segments[i + 1].start - segments[i].start;
        } else {
          segments[i].duration = 5; // Default for last segment
        }
      }
      
      const result = {
        videoId: videoId,
        title: document.title.replace(' - YouTube', ''),
        languageCode: 'unknown',
        isAutoGenerated: false,
        segments: segments,
        extractedAt: new Date().toISOString(),
        source: 'bookmarklet-dom'
      };
      
      const json = JSON.stringify(result, null, 2);
      navigator.clipboard.writeText(json).then(() => {
        alert('✅ Transcript copied from open panel!\\n\\nSegments: ' + segments.length + '\\n\\nPaste it in the DoubleCheck AI import box.');
      }).catch(err => {
        prompt('Could not copy automatically. Copy this JSON manually:', json);
      });
      return;
    }
  } catch (e) {
    console.error('Error extracting from DOM:', e);
  }

  alert('❌ Could not find transcript data.\\n\\nTry these steps:\\n1. Click the ⋯ button below the video\\n2. Click "Show transcript"\\n3. Run this bookmarklet again\\n\\nNote: Some videos may not have transcripts available.');
})();
`;

/**
 * Generates the bookmarklet URL (javascript: URI)
 */
export function generateBookmarkletUrl(): string {
  // Minify the code (basic minification)
  const minified = BOOKMARKLET_SOURCE
    .replace(/\/\/.+$/gm, '') // Remove single-line comments
    .replace(/\s+/g, ' ') // Collapse whitespace
    .replace(/\s*([{};,:])\s*/g, '$1') // Remove space around punctuation
    .trim();

  return 'javascript:' + encodeURIComponent(minified);
}

/**
 * Generates the full bookmarklet anchor element HTML
 */
export function generateBookmarkletHtml(name: string = 'Get YT Transcript'): string {
  const url = generateBookmarkletUrl();
  return `<a href="${url}" title="Drag this to your bookmarks bar">${name}</a>`;
}

/**
 * Returns the raw (non-minified) bookmarklet source for debugging
 */
export function getBookmarkletSource(): string {
  return BOOKMARKLET_SOURCE.trim();
}
