/**
 * Utilities for exporting and importing transcript data
 * Allows saving transcript data for faster development/testing without fetching from YouTube
 */

export interface TranscriptSegment {
  start: number;
  duration: number;
  text: string;
}

export interface TranscriptData {
  videoId: string;
  languageCode: string;
  isAutoGenerated: boolean;
  segments: TranscriptSegment[];
  sessionId?: string;
}

export interface TranscriptExport {
  version: '1.0';
  exportedAt: string;
  transcript: TranscriptData;
}

/**
 * Exports transcript data to JSON format
 */
export function exportTranscriptAsJson(transcript: TranscriptData): string {
  const exportData: TranscriptExport = {
    version: '1.0',
    exportedAt: new Date().toISOString(),
    transcript,
  };
  return JSON.stringify(exportData, null, 2);
}

/**
 * Downloads transcript data as JSON file
 */
export function downloadTranscriptJson(transcript: TranscriptData, videoId: string = 'transcript'): void {
  const json = exportTranscriptAsJson(transcript);
  const blob = new Blob([json], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${videoId}-transcript-${new Date().toISOString().split('T')[0]}.json`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Exports transcript data to formatted text with timestamps
 */
export function exportTranscriptAsText(segments: TranscriptSegment[]): string {
  return segments
    .map(segment => `[${formatTimestamp(segment.start)}] ${segment.text}`)
    .join('\n');
}

/**
 * Downloads transcript as formatted text file
 */
export function downloadTranscriptText(segments: TranscriptSegment[], videoId: string = 'transcript'): void {
  const text = exportTranscriptAsText(segments);
  const blob = new Blob([text], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${videoId}-transcript-${new Date().toISOString().split('T')[0]}.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Parses transcript from JSON text
 */
export function parseTranscriptFromJson(jsonText: string): TranscriptData {
  try {
    const data: TranscriptExport = JSON.parse(jsonText);
    if (!data.transcript) {
      throw new Error('Invalid transcript format: missing "transcript" property');
    }
    return data.transcript;
  } catch (error: any) {
    throw new Error(`Failed to parse transcript JSON: ${error.message}`);
  }
}

/**
 * Parses transcript from plain text format
 * Expects format: [HH:MM:SS] text
 */
export function parseTranscriptFromText(text: string): TranscriptSegment[] {
  const lines = text.split('\n').filter(line => line.trim());
  const segments: TranscriptSegment[] = [];

  for (const line of lines) {
    // Match pattern: [HH:MM:SS] text or [MM:SS] text
    const match = line.match(/^\[(\d{1,2}):(\d{2}):(\d{2})\]\s+(.+)$|^\[(\d{1,2}):(\d{2})\]\s+(.+)$/);
    
    if (match) {
      let start: number;
      let text: string;

      if (match[1] !== undefined) {
        // HH:MM:SS format
        const hours = parseInt(match[1], 10);
        const minutes = parseInt(match[2], 10);
        const seconds = parseInt(match[3], 10);
        start = hours * 3600 + minutes * 60 + seconds;
        text = match[4];
      } else {
        // MM:SS format
        const minutes = parseInt(match[5], 10);
        const seconds = parseInt(match[6], 10);
        start = minutes * 60 + seconds;
        text = match[7];
      }

      segments.push({
        start,
        duration: 0, // Will be calculated
        text,
      });
    }
  }

  // Calculate durations
  for (let i = 0; i < segments.length; i++) {
    if (i < segments.length - 1) {
      segments[i].duration = segments[i + 1].start - segments[i].start;
    } else {
      segments[i].duration = 0; // Last segment duration unknown
    }
  }

  return segments;
}

/**
 * Formats seconds as HH:MM:SS timestamp
 */
export function formatTimestamp(seconds: number): string {
  const hours = Math.floor(seconds / 3600);
  const minutes = Math.floor((seconds % 3600) / 60);
  const secs = Math.floor(seconds % 60);
  return `${hours.toString().padStart(2, '0')}:${minutes.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`;
}
