import mongoose, { Schema, Document } from 'mongoose';
import { TopicGroup } from '../types';

export interface IAnalysisSession extends Document {
  userId: string;
  sourceUrl: string;
  sourceType: 'youtube' | 'article' | 'text';
  status: 'created' | 'extracting_transcript' | 'analyzing_topics' | 'identifying_speakers' | 'grouping_dialog' | 'completed' | 'failed';
  
  // Step 1: Transcript
  transcript: {
    videoId: string;
    languageCode: string;
    isAutoGenerated: boolean;
    segments: Array<{
      start: number;
      duration: number;
      text: string;
    }>;
  };
  
  // Step 1.5: Transcript Blocks (prepared for analysis)
  transcriptBlocks: Array<{
    blockId: string;
    startTime: number;
    endTime: number;
    text: string;
    segmentTiming: Array<{
      start: number;
      end: number;
      text: string;
    }>;
  }>;
  
  // Step 2: Topic Analysis
  topicAnalysis: Array<{
    blockId: string;
    startTime: number;
    endTime: number;
    text: string;
    mainTopics: string[];
    tags: Array<{
      tag: string;
      relevance: number;
      importance: number;
      frequency: number;
    }>;
    summary: string;
  }>;
  
  // Step 2.5: Selected block IDs for speaker analysis
  selectedBlockIds: string[];
  
  // Step 3: Speaker Identification
  speakerAnalysis: Array<{
    blockId: string;
    startTime: number;
    endTime: number;
    speakers: Array<{
      id: string;
      name: string;
    }>;
    dialogue: Array<{
      id: string;
      speakerId: string;
      speaker: string;
      text: string;
      startTime: number;
      endTime: number;
      timingMismatch?: boolean;
    }>;
    identifiedSpeakers: string[];
  }>;
  
  // Step 4: Dialog Analysis
  dialogAnalysis: TopicGroup[];
  
  createdAt: Date;
  updatedAt: Date;
  error?: string;
}

const AnalysisSessionSchema: Schema = new Schema({
  userId: { type: String, required: true },
  sourceUrl: { type: String, required: true },
  sourceType: { type: String, enum: ['youtube', 'article', 'text'], default: 'youtube' },
  status: { 
    type: String, 
    enum: ['created', 'extracting_transcript', 'analyzing_topics', 'identifying_speakers', 'grouping_dialog', 'completed', 'failed'],
    default: 'created'
  },
  
  transcript: {
    videoId: String,
    languageCode: String,
    isAutoGenerated: Boolean,
    segments: [{
      start: Number,
      duration: Number,
      text: String
    }]
  },
  
  transcriptBlocks: [{
    blockId: String,
    startTime: Number,
    endTime: Number,
    text: String,
    segmentTiming: [{
      start: Number,
      end: Number,
      text: String
    }]
  }],
  
  topicAnalysis: [{
    blockId: String,
    startTime: Number,
    endTime: Number,
    text: String,
    mainTopics: [String],
    tags: [{
      tag: String,
      relevance: Number,
      importance: Number,
      frequency: Number
    }],
    summary: String
  }],
  
  selectedBlockIds: [String],
  
  speakerAnalysis: [{
    blockId: String,
    startTime: Number,
    endTime: Number,
    speakers: [{
      id: String,
      name: String
    }],
    dialogue: [{
      id: String,
      speakerId: String,
      speaker: String,
      text: String,
      startTime: Number,
      endTime: Number,
      timingMismatch: Boolean
    }],
    identifiedSpeakers: [String]
  }],
  
  dialogAnalysis: [Schema.Types.Mixed],
  
  error: String
}, {
  timestamps: true,
  // Ensure we respect environment-based collection suffix for multi-tenant/dev separation
  collection: `analysissessions${process.env.DB_COLLECTION_SUFFIX || ''}`,
});

export default mongoose.model<IAnalysisSession>('AnalysisSession', AnalysisSessionSchema);
