import mongoose, { Schema, Document } from 'mongoose';
import { TopicGroup } from '../types';

export interface IContentAnalysis extends Document {
  userId: string;
  sourceUrl: string;
  sourceType: 'youtube' | 'article' | 'text';
  
  // Metadata
  title?: string;
  description?: string;
  publishedAt?: Date;
  languageCode?: string;
  languageName?: string;
  
  // Step 1: Transcript
  transcript: {
    videoId: string;
    languageCode: string;
    isAutoGenerated: boolean;
    segments: Array<{
      start: number;
      duration: number;
      text: string;
    }>;
  };
  
  // Step 1.5: Transcript Blocks (prepared for analysis)
  transcriptBlocks: Array<{
    blockId: string;
    startTime: number;
    endTime: number;
    text: string;
  }>;
  
  // Step 2: Topic Analysis
  topicAnalysis: Array<{
    blockId: string;
    startTime: number;
    endTime: number;
    text: string;
    mainTopics: string[];
    tags: Array<{
      tag: string;
      relevance: number;
      importance: number;
      frequency: number;
    }>;
    summary: string;
  }>;
  
  // Step 3: Speaker Identification
  speakerAnalysis: Array<{
    blockId: string;
    startTime: number;
    endTime: number;
    dialogue: Array<{
      speaker: string;
      text: string;
    }>;
    identifiedSpeakers: string[];
  }>;
  
  // Step 4: Dialog Analysis
  dialogAnalysis: TopicGroup[];
  
  createdAt: Date;
  updatedAt: Date;
}

const ContentAnalysisSchema: Schema = new Schema({
  userId: { type: String, required: true, index: true },
  sourceUrl: { type: String, required: true },
  title: String,
  description: String,
  publishedAt: Date,
  languageCode: String,
  languageName: String,
  
  transcript: {
    videoId: String,
    languageCode: String,
    isAutoGenerated: Boolean,
    segments: [{
      start: Number,
      duration: Number,
      text: String
    }]
  },
  
  transcriptBlocks: [{
    blockId: String,
    startTime: Number,
    endTime: Number,
    text: String
  }],
  
  topicAnalysis: [{
    blockId: String,
    startTime: Number,
    endTime: Number,
    text: String,
    mainTopics: [String],
    tags: [{
      tag: String,
      relevance: Number,
      importance: Number,
      frequency: Number
    }],
    summary: String
  }],
  
  speakerAnalysis: [{
    blockId: String,
    startTime: Number,
    endTime: Number,
    dialogue: [{
      speaker: String,
      text: String
    }],
    identifiedSpeakers: [String]
  }],
  
  dialogAnalysis: [{
    id: String,
    title: String,
    dialogLines: [{
      speaker: String,
      text: String,
      timestamp: Number
    }],
    analysis: {
      summaryItems: [{
        text: String,
        timestamp: String,
        importance: Number,
        isSelected: Boolean,
        groupId: Number
      }]
    }
  }]
}, {
  timestamps: true
});

const collectionName = `contentanalyses${process.env.DB_COLLECTION_SUFFIX || ''}`;

export default (mongoose.models.ContentAnalysis as mongoose.Model<IContentAnalysis>) || mongoose.model<IContentAnalysis>('ContentAnalysis', ContentAnalysisSchema, collectionName);
