import { JSDOM } from 'jsdom';

// --- Types ---

export interface TranscriptSegment {
  start: number;
  duration: number;
  text: string;
}

export interface TranscriptResult {
  videoId: string;
  languageCode: string;
  isAutoGenerated: boolean;
  segments: TranscriptSegment[];
}

/**
 * Formats seconds as HH:MM:SS timestamp
 */
function formatTimestamp(seconds: number): string {
  const hours = Math.floor(seconds / 3600);
  const minutes = Math.floor((seconds % 3600) / 60);
  const secs = Math.floor(seconds % 60);
  return `${hours.toString().padStart(2, '0')}:${minutes.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`;
}

/**
 * Constructs a formatted transcript text with timestamps
 * Each segment is formatted as "[HH:MM:SS] text"
 */
export function constructFormattedTranscript(segments: TranscriptSegment[]): string {
  return segments
    .map(segment => `[${formatTimestamp(segment.start)}] ${segment.text}`)
    .join('\n');
}

export type YoutubeTranscriptErrorCode = 
  | 'CAPTIONS_NOT_FOUND' 
  | 'VIDEO_RESTRICTED' 
  | 'INVALID_VIDEO_ID' 
  | 'NETWORK_ERROR' 
  | 'PARSING_ERROR';

export class YoutubeTranscriptError extends Error {
  code: YoutubeTranscriptErrorCode;
  constructor(message: string, code: YoutubeTranscriptErrorCode) {
    super(message);
    this.code = code;
    this.name = 'YoutubeTranscriptError';
  }
}

interface CaptionTrack {
  baseUrl: string;
  name: { simpleText: string };
  vssId: string;
  languageCode: string;
  kind?: string;
  isTranslatable: boolean;
}

// --- Constants ---

const USER_AGENT = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36';

// --- Core Logic ---

/**
 * Extracts the YouTube Video ID from a given URL or string.
 */
export function extractVideoId(input: string): string {
  if (!input) {
    throw new YoutubeTranscriptError('Input is empty', 'INVALID_VIDEO_ID');
  }

  // If input is already 11 chars and matches the pattern, assume it's an ID
  if (/^[a-zA-Z0-9_-]{11}$/.test(input)) {
    return input;
  }

  // Common patterns
  const patterns = [
    /(?:v=|v\/|vi\/|youtu\.be\/|embed\/|shorts\/)([\w-]{11})/,
    /^([\w-]{11})$/
  ];

  for (const pattern of patterns) {
    const match = input.match(pattern);
    if (match && match[1]) {
      return match[1];
    }
  }

  throw new YoutubeTranscriptError('Could not parse video ID', 'INVALID_VIDEO_ID');
}

/**
 * Fetches the watch page to extract the Innertube API Key.
 */
async function getInnertubeApiKey(videoId: string): Promise<string> {
  const watchUrl = `https://www.youtube.com/watch?v=${videoId}`;
  
  let html: string;
  try {
    console.log(`[YouTube] Fetching watch page for videoId: ${videoId}`);
    const response = await fetch(watchUrl, {
      headers: { 'User-Agent': USER_AGENT }
    });
    
    if (!response.ok) {
      console.error(`[YouTube] Watch page fetch failed: HTTP ${response.status}`);
      throw new Error(`HTTP ${response.status}`);
    }
    html = await response.text();
    console.log(`[YouTube] Watch page fetched successfully, length: ${html.length}`);
  } catch (error) {
    console.error(`[YouTube] Failed to fetch watch page: ${(error as Error).message}`);
    throw new YoutubeTranscriptError(`Failed to fetch watch page: ${(error as Error).message}`, 'NETWORK_ERROR');
  }

  // Check for restriction
  if (html.includes('og:restricted:age')) {
    console.log(`[YouTube] Video is age restricted`);
    throw new YoutubeTranscriptError('Video is age restricted', 'VIDEO_RESTRICTED');
  }

  // Extract API Key
  const keyMatch = html.match(/"INNERTUBE_API_KEY"\s*:\s*"([^"]+)"/);
  if (!keyMatch || !keyMatch[1]) {
    // Fallback: sometimes it's in a different format or not present for some videos, 
    // but usually it is there for the player.
    // We could also try to find 'innertubeApiKey'
    const keyMatch2 = html.match(/innertubeApiKey"\s*:\s*"([^"]+)"/);
    if (keyMatch2 && keyMatch2[1]) {
      console.log(`[YouTube] API key extracted via fallback regex: ${keyMatch2[1].substring(0, 10)}...`);
      return keyMatch2[1];
    }
    console.error(`[YouTube] Could not extract INNERTUBE_API_KEY from HTML`);
    throw new YoutubeTranscriptError('Could not extract INNERTUBE_API_KEY', 'PARSING_ERROR');
  }

  console.log(`[YouTube] API key extracted: ${keyMatch[1].substring(0, 10)}...`);
  return keyMatch[1];
}

/**
 * Calls the Innertube Player API to get caption tracks.
 */
async function getCaptionTracks(videoId: string, apiKey: string): Promise<CaptionTrack[]> {
  const playerUrl = `https://www.youtube.com/youtubei/v1/player?key=${apiKey}`;
  
  const body = {
    context: {
      client: {
        clientName: 'WEB',
        clientVersion: '2.20241201.01.00',
        hl: 'en',
        gl: 'US',
        utcOffsetMinutes: 0,
        clientScreen: 'WATCH',
      },
    },
    videoId: videoId,
  };

  let data: any;
  try {
    console.log(`[YouTube] Calling Player API for videoId: ${videoId}`);
    console.log(`[YouTube] Request body:`, JSON.stringify(body, null, 2));
    const response = await fetch(playerUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'User-Agent': USER_AGENT,
      },
      body: JSON.stringify(body),
    });

    console.log(`[YouTube] Player API response status: ${response.status}`);
    if (!response.ok) {
      const errorText = await response.text();
      console.error(`[YouTube] Player API error response: ${errorText}`);
      throw new Error(`HTTP ${response.status}`);
    }
    data = await response.json();
    console.log(`[YouTube] Player API response received successfully`);
  } catch (error) {
    console.error(`[YouTube] Failed to call Player API: ${(error as Error).message}`);
    throw new YoutubeTranscriptError(`Failed to call Player API: ${(error as Error).message}`, 'NETWORK_ERROR');
  }

  // Check for playability status
  if (data.playabilityStatus && data.playabilityStatus.status !== 'OK') {
    console.log(`[YouTube] Playability status: ${data.playabilityStatus.status}`);
    if (data.playabilityStatus.status === 'UNPLAYABLE') {
       throw new YoutubeTranscriptError('Video is unplayable or restricted', 'VIDEO_RESTRICTED');
    }
  }

  const captions = data.captions?.playerCaptionsTracklistRenderer?.captionTracks;
  if (!captions || !Array.isArray(captions) || captions.length === 0) {
    console.log(`[YouTube] No captions found in response`);
    throw new YoutubeTranscriptError('No captions found for this video', 'CAPTIONS_NOT_FOUND');
  }

  console.log(`[YouTube] Found ${captions.length} caption tracks`);
  return captions as CaptionTrack[];
}

/**
 * Selects the best caption track based on language preference.
 */
function selectCaptionTrack(tracks: CaptionTrack[], preferredLang: string = 'en'): CaptionTrack {
  console.log(`[YouTube] Selecting caption track from ${tracks.length} tracks, preferred language: ${preferredLang}`);
  tracks.forEach((track, i) => {
    console.log(`[YouTube] Track ${i}: lang=${track.languageCode}, kind=${track.kind}, name=${track.name.simpleText}`);
  });

  // 1. Exact match
  const exactMatch = tracks.find(t => t.languageCode === preferredLang);
  if (exactMatch) {
    console.log(`[YouTube] Selected exact match: ${exactMatch.languageCode}`);
    return exactMatch;
  }

  // 2. Prefix match (e.g. 'en' matches 'en-US')
  const prefixMatch = tracks.find(t => t.languageCode.startsWith(preferredLang));
  if (prefixMatch) {
    console.log(`[YouTube] Selected prefix match: ${prefixMatch.languageCode}`);
    return prefixMatch;
  }

  // 3. English fallback if preferred was not english
  if (preferredLang !== 'en') {
      const enMatch = tracks.find(t => t.languageCode.startsWith('en'));
      if (enMatch) {
        console.log(`[YouTube] Selected English fallback: ${enMatch.languageCode}`);
        return enMatch;
      }
  }

  // 4. First available
  console.log(`[YouTube] Selected first available: ${tracks[0].languageCode}`);
  return tracks[0];
}

/**
 * Fetches and parses the XML transcript.
 */
async function fetchAndParseTranscript(track: CaptionTrack): Promise<TranscriptSegment[]> {
  console.log(`[YouTube] Fetching transcript XML from: ${track.baseUrl}`);
  let xml: string;
  try {
    const response = await fetch(track.baseUrl);
    if (!response.ok) {
      console.error(`[YouTube] Transcript fetch failed: HTTP ${response.status}`);
      throw new Error(`HTTP ${response.status}`);
    }
    xml = await response.text();
    console.log(`[YouTube] Transcript XML fetched, length: ${xml.length}`);
  } catch (error) {
    console.error(`[YouTube] Failed to fetch transcript XML: ${(error as Error).message}`);
    throw new YoutubeTranscriptError(`Failed to fetch transcript XML: ${(error as Error).message}`, 'NETWORK_ERROR');
  }

  try {
    console.log(`[YouTube] Parsing transcript XML`);
    const dom = new JSDOM(xml, { contentType: "text/xml" });
    const doc = dom.window.document;
    const textElements = doc.querySelectorAll('text');

    const segments: TranscriptSegment[] = [];
    
    textElements.forEach(el => {
      const start = parseFloat(el.getAttribute('start') || '0');
      const duration = parseFloat(el.getAttribute('dur') || '0');
      let text = el.textContent || '';

      // Decode HTML entities (JSDOM does this automatically for textContent, but let's be safe if we need extra cleaning)
      // Clean up text
      text = text.replace(/&#39;/g, "'").replace(/&quot;/g, '"').trim();
      
      // Skip empty segments
      if (!text) return;

      segments.push({ start, duration, text });
    });

    console.log(`[YouTube] Parsed ${segments.length} transcript segments`);
    return segments;
  } catch (error) {
    console.error(`[YouTube] Failed to parse transcript XML: ${(error as Error).message}`);
    throw new YoutubeTranscriptError(`Failed to parse transcript XML: ${(error as Error).message}`, 'PARSING_ERROR');
  }
}

/**
 * Main entry point: Retrieves the transcript for a given YouTube video.
 */
export async function getTranscript(videoIdOrUrl: string, language: string = 'en'): Promise<TranscriptResult> {
  try {
    console.log(`[YouTube] Starting transcript extraction for: ${videoIdOrUrl}, language: ${language}`);
    const videoId = extractVideoId(videoIdOrUrl);
    console.log(`[YouTube] Extracted videoId: ${videoId}`);

    // 1. Get API Key
    const apiKey = await getInnertubeApiKey(videoId);

    // 2. Get Caption Tracks
    const tracks = await getCaptionTracks(videoId, apiKey);

    // 3. Select Track
    const selectedTrack = selectCaptionTrack(tracks, language);

    // 4. Fetch and Parse
    const segments = await fetchAndParseTranscript(selectedTrack);

    const result = {
      videoId,
      languageCode: selectedTrack.languageCode,
      isAutoGenerated: selectedTrack.kind === 'asr',
      segments
    };
    console.log(`[YouTube] Transcript extraction successful: ${segments.length} segments, lang: ${selectedTrack.languageCode}, auto: ${selectedTrack.kind === 'asr'}`);
    return result;

  } catch (error) {
    if (error instanceof YoutubeTranscriptError) {
      console.error(`[YouTube] Transcript extraction failed with code: ${error.code}, message: ${error.message}`);
      throw error;
    }
    // Wrap unknown errors
    console.error(`[YouTube] Unexpected error: ${(error as Error).message}`);
    throw new YoutubeTranscriptError(`Unexpected error: ${(error as Error).message}`, 'PARSING_ERROR');
  }
}
